### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by aleworth** [kriscross07/atom-gpp-compiler#134]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Bad argument

```
At internal/child_process.js:289

TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at HTMLLIElement.treeCompile (/packages/gpp-compiler/index.js:251:3)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.20.1/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.20.1/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:18.7.0 gpp-compiler:tree-compile (li.file.entry.list-item.selected)
     -2:28.5.0 grammar-selector:show (atom-text-editor.editor.has-selection)
     -0:30.3.0 core:confirm (input.hidden-input)
     -0:13.5.0 gpp-compiler:tree-compile (li.file.entry.list-item.selected)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by Danpepboy** [comment]
How do you fix ??

**Comment by JoseBenavidesG** [comment]
I have the same problem!!!, How fixed this?

**Comment by JoseBenavidesG** [comment]
I uninstall and then install again , but not work !!! :(

**Comment by Danpepboy** [comment]
wow nobody has any idea how to fix this???

**Comment by birhman** [comment]
I was working on a python script and got same error. I just uninstalled all the gcc packages and it worked for me.

**Comment by JoseBenavidesG** [comment]
Now work for me, I uninstall ALL packaqes for C++ in Atom, as linter, gpp compiler. etc... Then reinstall Atom-gpp-compiler and work good.

Ahora trabaja para mi, Yo desintale TODOS los paquetes para C++, como linter, compilador GPP, etc... Luego reinstale Atom-gpp-compiler y trabaja bien.

**Comment by vivek-kumar9696** [comment]
In my experience this error occurs when Atom cannot recognize the type of code you are trying to run.
**Select the highlighted tab in the lower right section of the pic below and change language type manually.**
![capture](https://user-images.githubusercontent.com/31619951/31304897-b0900c7e-ab4a-11e7-803c-b34168895ed3.PNG)

Hope this helps!

**Comment by avsingh999** [comment]
anyone have another idea please tell

**Comment by GuesmiKhaled** [comment]
well i have the same error and i think the compilator doesn't work ??

**Comment by avsingh999** [comment]
I have disabled the package than another compiler working

**Comment by himstien** [comment]
I was having the same issue when trying to make and run from Makefile.
I solved it by adding the lines:
run:
    ./${PROJECTNAME}


Replace ${PROJECTNAME} with the name of the output file that is created after make. like so:

#=========================================================================
run:
	./FARMS_Flow

After this, either right click on MakeFile and click "Make and Run" or press F6.

**My guess on the problem:** I think that the compiler is able to compile (make) the project without problem but when it tries to "run" the program it encounters "bad argument" as the name of the program is either wrong or not available.

**Comment by Hyeon9mak** [comment]
Have same problem.

**Comment by shashank-sharma** [comment]
I was also facing the same issue and I suggest to follow this comment:
https://github.com/kriscross07/atom-gpp-compiler/issues/46#issuecomment-254782751

Just go to `~/.atom/` and do:
`mv packages ~/.` (or any other directory)
Now start your atom/restart it and then install gpp-compiler
Now you should be able to run it nicely. I am not sure what's the reason behind this. According to me I guess language-cpp14 package is causing this error.

**Comment by theamiteshtripathi** [comment]
I was having the same problem, In my case, I'm having both atom-python-run package and gpp-compiler package for languages python and c/c++ respectively. While using pyhton code I just disabled the gpp-compiler because both packages compile and run by F5 key, so just disable gpp-compiler.

You can disable gpp-compiler by: ctrl+,  >  packages  > search for gpp-compiler> diable from there.
Thanks!

**Comment by vincentlarkin** [comment]
Wow, really sad that a simple feature (not saying the code is simple, just simple premise that SHOULD work in ANY IDE) doesn't work. Sad! Getting the same error.
@amit-tripathi2511 Well some people need the C functionality also, which doesn't work with F5
If somebody has a REAL fix, I'd be glad to hear it.

**Comment by Nimrod0901** [comment]
Actually, there is no need to disable gpp-package
You can change the conflict keybinding 'F5' into other keybindings.

**Comment by Nimrod0901** [comment]
Just `ctrl+shift+p > Show keybindings > Search keybindings > 'F5'`
Select the conflicting command and change it in your own keymap.

**Comment by Kurtoid** [comment]
Is there a way to prevent "Compile and run" from showing up in the context menu for a file in another language?
