### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by xiaoyu9964** [kriscross07/atom-gpp-compiler#15]
my platform is windows. GCC and G++ command is usable in cmd. 
C:\Users\SNY\.atom\packages\gpp-compiler\index.js:125
Hide Stack Trace
TypeError: Cannot read property 'path' of null
    at atom-text-editor.compileGpp (C:\Users\SNY\.atom\packages\gpp-compiler\index.js:125:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\SNY\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\SNY\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\SNY\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\SNY\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\SNY\AppData\Local\atom\app-1.7.2\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\SNY\AppData\Local\atom\app-1.7.2\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by kriscross07** [comment]
I am unable to replicate this bug. Try every plugin except for gpp-compiler and try again.

**Comment by kriscross07** [comment]
gpp-compiler v2.3.0 fixes this issue, thanks to [farnabaz](https://github.com/farnabaz).
