### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by septnight** [kriscross07/atom-gpp-compiler#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0-beta6
**System**: Mac OS X 10.11.1
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package, v0.3.6

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1036

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1036:15)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1030:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:588:26)
    at atom-text-editor.compile (/Users/molin/.atom/packages/gpp-compiler/index.js:20:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -1:02.1.0 gpp-compiler:compile (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
gpp-compiler, v0.3.6
language-cpp14, v0.4.2

# Dev
No dev packages
```

**Comment by kriscross07** [comment]
Have you saved the file? You need to save a file before compiling it.

Also, I just released an update that should make the package compatible with Mac, so tell me if anything doesn't work. After you update the package, make sure to restart Atom so everything works properly.
