### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by DauntlessRony** [kriscross07/atom-gpp-compiler#201]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.8.4
**OS**: "Arch Linux"
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:392

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:392:11)
    at Object.exports.spawn (child_process.js:499:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:110:34)
```

### Commands

```
     -0:42.4.0 gpp-compiler:compile (input.hidden-input)
     -0:27.6.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:19.6.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
     -0:10.2.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by Raghav905** [comment]
i am also getting this issue. pls someone tell how to resolve this

**Comment by RifqiOnky** [comment]
Me too

 [Enter steps to reproduce:]

1. Press fn+f5 to run the code

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  2x -5:25.8.0 gpp-compiler:compile (input.hidden-input)
  4x -3:14.6.0 core:backspace (input.hidden-input)
     -3:02.4.0 core:move-left (input.hidden-input)
     -3:02.1.0 core:backspace (input.hidden-input)
  2x -2:59.1.0 core:confirm (input.hidden-input)
     -2:32.1.0 gpp-compiler:compile (input.hidden-input)
  2x -2:22 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
latex 0.50.0 
latex-completions 0.3.3 
linter-spell-latex 0.11.0 
markdown-writer 2.7.4 
open-html-in-browser 0.2.1 
```

**Comment by ali-falah** [comment]
I am also have the same issue

**Comment by miliaCC** [comment]
So anyone could save my atom?

**Comment by Nkoumpis** [comment]
Try to specify the type of file that you want to use . For example if you want to start a cpp file you have to put, "filename".cpp

**Comment by dvincicodes** [comment]
@RifqiOnky  Make sure the bottom left says C and not Plain Text or anything else. 

![image](https://user-images.githubusercontent.com/969208/42793127-b15c07e0-8946-11e8-9aac-3ae76a88ebe7.png)

**Comment by aliald** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 ia32
**Electron**: 2.0.5
**OS**: ??Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.2/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.28.2/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.28.2/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.28.2/resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -7:07.2.0 application:open-file (input.hidden-input)
     -5:28.4.0 core:paste (div.line.cursor-line)
     -5:23.7.0 core:save-as (input.hidden-input)
     -4:50.6.0 gpp-compiler:compile (div.line)
  3x -4:28.3.0 core:backspace (input.hidden-input)
     -4:14.9.0 core:confirm (input.hidden-input)
     -0:40.9.0 core:save-as (input.hidden-input)
     -0:15.3.0 gpp-compiler:compile (div.line.cursor-line)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
my-package 0.0.0 
```

why i can not run html and show me this

**Comment by fangzhou-xie** [comment]
> @RifqiOnky Make sure the bottom left says C and not Plain Text or anything else.
> 
> ![image](https://user-images.githubusercontent.com/969208/42793127-b15c07e0-8946-11e8-9aac-3ae76a88ebe7.png)

I solved my problem by using your idea. I was having "c++14" and I changed it to "c++" and it works. Thank you very much!
