### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by Sophoca** [kriscross07/atom-gpp-compiler#219]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:323

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:13.2.0 gpp-compiler:compile (input.hidden-input)
     -0:39.6.0 tabs:split-right (div.title.icon.c-icon.medium-blue.temp)
     -0:11.2.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.21 
git-plus 7.10.2 
gpp-compiler 3.0.7 
highlight-selected 0.13.1 
ide-cpp 0.0.3 
intentions 1.1.5 
linter 2.2.0 
linter-clang 4.1.2 
linter-cpplint 2.0.1 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
```

**Comment by jagon12345** [comment]
in package Settings, selecting wrong linux ternimal type will cause this  error, 
so i changed XTerm to GNOME Terminal, and it worked for me.

**Comment by Baitinq** [comment]
This happens to me too, i cant fix it
