### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by hassnain922** [kriscross07/atom-gpp-compiler#227]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 ia32
**Electron**: 2.0.5
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.29.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.29.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -8:14.4.0 core:move-left (input.hidden-input)
     -3:23.8.0 application:open-file (div.panels-item)
  2x -3:11.6.0 gpp-compiler:compile (div.line)
     -1:15.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:03.6.0 core:save-as (input.hidden-input)
 13x -0:38.6.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
ide-cpp 0.0.3 
language-cpp14 0.6.2 
linter-gcc 0.7.1 
script 3.18.1 
```

**Comment by rjgupta** [comment]
The error I believe is because you don't have a proper extension of the file.

**Comment by ZdrytchX** [comment]
Pressing CTR+F6 to pull down the custom compile menu, pressing ESC to close that and then pressing F6 seems to do the job for me. Atom sure is weird.

[![fixmeplz](https://img.youtube.com/vi/Vv8JCnt17lA/0.jpg)](https://www.youtube.com/watch?v=Vv8JCnt17lA)

**Comment by leonelramos** [comment]
all my files have the .rb extension and run fine if I compile them in my terminal but I always get this If i try through Atom
