### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by Sumanth-Prasad** [kriscross07/atom-gpp-compiler#233]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.30.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.30.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -3:08.1.0 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -3:05.3.0 core:backspace (input.hidden-input)
     -3:00.9.0 core:confirm (input.hidden-input)
     -2:57.9.0 core:paste (input.hidden-input)
     -2:54.6.0 core:backspace (input.hidden-input)
     -2:51.6.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -2:47 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:48.7.0 core:paste (input.hidden-input)
     -1:40.6.0 gpp-compiler:gdb (div.highlights)
  2x -1:35.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  4x -1:27.5.0 core:backspace (input.hidden-input)
 11x -0:27.5.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
ide-java 0.8.3 
```

**Comment by inweblife** [comment]
Uncaught TypeError: "file" argument must be a non-empty string
child_process.js:395
Hide Stack Trace
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at compile (C:\Users\ivan7\.atom\packages\gpp-compiler\index.js:274:31)
    at compileFile (C:\Users\ivan7\.atom\packages\gpp-compiler\index.js:216:5)
    at HTMLElement.gpp-compiler:compile (C:\Users\ivan7\.atom\packages\gpp-compiler\index.js:23:11)
    at CommandRegistry.handleCommandEvent (C:\Users\ivan7\AppData\Local\atom\app-1.31.2\resources\app\src\command-registry.js:384:49)
    at CommandRegistry.dispatch (C:\Users\ivan7\AppData\Local\atom\app-1.31.2\resources\app\src\command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (C:\Users\ivan7\AppData\Local\atom\app-1.31.2\resources\app\src\atom-environment.js:1355:25)
    at EventEmitter.outerCallback (C:\Users\ivan7\AppData\Local\atom\app-1.31.2\resources\app\src\application-delegate.js:318:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)

**Comment by FiresPOW** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.12
**OS**: "Manjaro Linux"
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at HTMLLIElement.treeCompile (/packages/gpp-compiler/index.js:251:3)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:384:43)
    at CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:273:17)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/lib/atom/src/atom-environment.js:1345:19)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:305:47)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
```
