### ISSUE TITLE
It does not work well with Javascript

### ISSUE THREAD

**Issue by ZhiyueLi** [kriscross07/atom-gpp-compiler#271]
When running atom for javascript, it will show you the error like child_process.js:409.

**Comment by karakunai** [comment]
What do you mean by 'running atom for javascript' ? I don't have any issues with my JS projects so far.

**Comment by ZhiyueLi** [comment]
Here is a simple example. When using atom for javascript, here is the screenshot.
![Screenshot (454)](https://user-images.githubusercontent.com/45377112/62272980-b6122700-b47f-11e9-9bdb-393c3564b24b.png)

**Comment by ZhiyueLi** [comment]
Here is error details:

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at normalizeSpawnArguments (child_process.js:409:11)
    at Object.spawn (child_process.js:534:38)
    at compile (C:\Users\zhiyu\.atom\packages\gpp-compiler\index.js:274:31)
    at compileFile (C:\Users\zhiyu\.atom\packages\gpp-compiler\index.js:216:5)
    at HTMLElement.gpp-compiler:compile (C:\Users\zhiyu\.atom\packages\gpp-compiler\index.js:23:11)
    at CommandRegistry.handleCommandEvent (C:\Users\zhiyu\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (C:\Users\zhiyu\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (C:\Users\zhiyu\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (C:\Users\zhiyu\AppData\Local\atom\app-1.39.1\resources\app\static\<embedded>:11:283942)

Thank you for your response.

**Comment by karakunai** [comment]
I can reproduce the bug, but then why would you try to compile a javascript with GCC/G++ compiler ?

**Comment by ZhiyueLi** [comment]
I am kind of new to atom. I just try different compiler. Thank you. I have just figure it out. By the way, is there any recommendation for packages in atom used for javascript ?

**Comment by karakunai** [comment]
Try [atom-runner](https://atom.io/packages/atom-runner), you don't need a compiler for a vanilla javascript, run it on a web browser, or try that one.
