### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by vish-xo** [kriscross07/atom-gpp-compiler#274]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Commands

```
     -2:50.2.0 gpp-compiler:compile (input.hidden-input)
  2x -2:23.3.0 core:backspace (input.hidden-input)
  7x -2:20.7.0 core:move-right (input.hidden-input)
     -2:18.7.0 core:save (input.hidden-input)
  8x -2:17 gpp-compiler:compile (input.hidden-input)
  2x -1:49.3.0 core:move-left (input.hidden-input)
  3x -1:48.2.0 core:move-down (input.hidden-input)
  3x -1:44 core:move-up (input.hidden-input)
  2x -1:41.6.0 core:move-down (input.hidden-input)
     -1:39.3.0 core:move-left (input.hidden-input)
  5x -1:38.9.0 core:move-down (input.hidden-input)
  5x -1:36.6.0 gpp-compiler:compile (input.hidden-input)
  6x -1:09.6.0 core:backspace (input.hidden-input)
 12x -1:07.8.0 core:delete (input.hidden-input)
     -1:01.7.0 core:save (input.hidden-input)
     -1:01.1.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
CutePastel-syntax 0.2.0 
gpp-compiler 3.0.7 
ide-java 0.9.0 
lanai-dark-syntax 0.11.0 
pink-pansy-ui 0.1.0 
```

**Comment by Efnuiwrbvu** [comment]
Have a similar problem :/

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:165

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:165:11)
    at Object.fs.unlink (fs.js:1048:14)
    at fs.stat (/packages/gpp-compiler/index.js:427:14)
    at FSReqWrap.oncomplete (fs.js:183:5)
```

### Commands

```
  5x -9:43.6.0 core:backspace (input.hidden-input)
     -2:14.5.0 tree-view:add-file (div.header.list-item.project-root-header)
     -2:08.5.0 core:confirm (input.hidden-input)
  4x -2:05.1.0 gpp-compiler:compile (input.hidden-input)
     -1:36.7.0 core:paste (input.hidden-input)
     -1:34.7.0 gpp-compiler:compile (input.hidden-input)
     -1:30.4.0 core:save (input.hidden-input)
  2x -1:29.1.0 gpp-compiler:compile (input.hidden-input)
     -0:05.0 core:backspace (input.hidden-input)
     -0:00.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6
atom-material-syntax 1.0.8
atom-material-ui 2.1.3
atom-python-run 0.9.7
autocomplete-html-entities 0.2.0
autocomplete-python 1.16.0
build 0.70.0
build-python 0.11.0
build-tools 4.5.13
busy-signal 2.0.1
export-html 3.1.0
flex-tool-bar 2.1.4
gpp-compiler 3.0.7
html-tab 1.0.2
html-to-css 0.2.2
Hydrogen 2.12.0
ide-html 0.6.0
ide-python 1.4.2
linter-gcc 0.7.1
platformio-ide-terminal 2.8.4
python-debugger 0.2.0
python-indent 1.2.3
python-line-profiler 0.3.2
python-runner 1.2.1
python-tools 0.6.9
rest-client 1.3.1
run-python-simply 0.6.0
script 3.18.1
tool-bar 1.1.12
```

**Comment by shreyash73** [comment]
how to repair this problem

**Comment by lovellbrooke77** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: "Fedora release
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
     -0:25.3.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:20.3.0 core:save (input.hidden-input)
     -0:18 gpp-compiler:gdb (div.line)
```

### Non-Core Packages

```
cpp-generator 1.0.1 
gpp-compiler 3.0.7 
```

:/ same problem

**Comment by MrSDT** [comment]
The same, Please guide how to solve this.
`
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro N
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Commands

```
     -7:11.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:05.7.0 autocomplete-plus:confirm (input.hidden-input)
     -7:05.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -7:00.5.0 core:backspace (input.hidden-input)
     -6:55.3.0 core:save (input.hidden-input)
     -6:53.4.0 gpp-compiler:compile (input.hidden-input)
     -6:01.8.0 gpp-compiler:gdb (input.hidden-input)
     -5:27 settings-view:install-packages-and-themes (a.stack-toggle)
     -4:45.8.0 cpp-compiler:compile (input.hidden-input)
  5x -4:24.6.0 core:backspace (input.hidden-input)
     -4:23.2.0 core:save (input.hidden-input)
     -4:22 cpp-compiler:compile (input.hidden-input)
     -4:18 cpp-compiler:compileAndRun (input.hidden-input)
  2x -2:00.2.0 gpp-compiler:compile (input.hidden-input)
  3x -0:24.9.0 core:backspace (input.hidden-input)
     -0:07.7.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
nv-dark-ui 3.0.8 
```


`

**Comment by lovellbrooke77** [comment]
Hi everyone, I un installed all packages and it looks as to compiler-invoker 1.1.0 works as when you hit f5. Try and install this compiler and see if it works.

**Comment by sinhaparth5** [comment]
Hi everyone, after installing gpp-compiler from atom, then you should install gpp and g++ from the terminal.
For Linux, open Terminal and run the command "sudo apt-get install gpp g++".
It helped me to overcome the uncaught callback issue in atom.
I hope you will also overcome this issue by my suggestion

**Comment by melonwrap** [comment]
> Hi everyone, I un installed all packages and it looks as to compiler-invoker 1.1.0 works as when you hit f5. Try and install this compiler and see if it works.

Unfortunately this didn't work, nor did sinhaparth5's solution. The issue remains persistent.

**Comment by htondev** [comment]
is someone find how to resolve that issue.? please

**Comment by GenyaLC** [comment]
I had a compilation error, Atom does not check your code before execute it.

**Comment by marhoganize** [comment]
The following solution at this link worked for me (I have a MAC):

(https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-mojave-update-xcrun-error-invalid-active-devel)

**Comment by SirYod** [comment]
Having this issue so hoping this replication bumps priority as I'd love for this to be fixed so I can start compiling...
Above solution appears to be Mac-only, which doesn't help other OS users. Glad it worked, though! :)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom:** 1.40.1 (x64)
**Electron:** 3.1.10
**OS:** Microsoft Windows 10 Pro
**Thrown From:** gpp-compiler package 3.0.7

### Stack Trace
_Uncaught Callback must be a function_

At fs.js:157

```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (\packages\gpp-compiler\index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Non-Core Packages
```
atom-clock 0.1.17 
atom-discord 2.0.2
atom-i18n 0.21.0
atom-java-decompiler 0.1.2
autocomplete-java 1.2.7
autocomplete-python 1.16.0
browser-plus 0.0.98
busy 0.7.0
emmet 2.4.3
git-control 0.9.0
gpp 0.4.3
gpp-compiler 3.0.7
ide-typescript 0.9.1
java-classpath-registry 0.4.0
java-import-wiz 0.5.0
java-importer 1.4.1
java-plus 0.1.0
open-in-browsers 0.0.30
sync-settings 0.8.6
tab-control 0.6.11
teletype 0.13.4
wakatime 7.1.1
```

**Comment by MSeutin** [comment]
I have a mac and I get this error too.  Please help

**Comment by UberHowley** [comment]
macOS Mojava 10.14.4 

## Steps to reproduce:

1. Get this error any time there's an error in the code (compiling C with the gpp package in atom). So, place error in C code.
2. Right click 'Compile and run' in Atom, using gpp package
3. This error doesn't appear if there aren't errors in the code.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.4
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Commands

```
     -3:49.4.0 core:backspace (input.hidden-input)
     -3:46.8.0 gpp-compiler:compile (span.syntax--punctuation.syntax--section.syntax--parens.syntax--end.syntax--bracket.syntax--round)
  4x -3:36.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by cedykcevna** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Commands

```
     -4:40.8.0 editor:newline (input.hidden-input)
     -4:35.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:31.8.0 core:undo (input.hidden-input)
     -4:26.3.0 core:move-right (input.hidden-input)
     -4:25.9.0 editor:newline (input.hidden-input)
     -4:21.9.0 core:move-up (input.hidden-input)
 10x -4:21.6.0 core:move-right (input.hidden-input)
     -4:18.2.0 editor:newline (input.hidden-input)
  2x -4:12.9.0 core:backspace (input.hidden-input)
  2x -4:09.7.0 editor:newline (input.hidden-input)
  2x -3:53.3.0 core:backspace (input.hidden-input)
     -3:48 editor:newline (input.hidden-input)
     -3:40.4.0 core:move-up (input.hidden-input)
     -3:17.7.0 core:backspace (input.hidden-input)
     -3:14.3.0 core:move-right (input.hidden-input)
     -3:00.8.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-i18n 0.21.0 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
autocomplete-clang 0.12.0 
busy-signal 2.0.1 
calamity-syntax 1.2.3 
dark-one-dark-syntax 2.3.0 
dark-syntax 0.0.2 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.0.0 
linter-clang 4.1.2 
linter-ui-default 1.8.0 
minimap 4.29.9 
script 3.18.1 
tree-view-sort 0.11.3 
vice-city-syntax 0.2.0 
```

**Comment by cedykcevna** [comment]
I was able to install everything to compile with ++) cheers everything works!

**Comment by cedykcevna** [comment]
I was able to install everything to compile with ++) cheers everything works!

**Comment by gloomydumber** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Commands

```
  2x -0:18.9.0 gpp-compiler:compile (input.hidden-input)
     -0:13.7.0 editor:newline (input.hidden-input)
     -0:13.2.0 gpp-compiler:compile (input.hidden-input)
  3x -0:10.5.0 core:backspace (input.hidden-input)
     -0:08.5.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-file-icons 0.7.1 
gpp-compiler 3.0.7 
highlight-selected 0.16.0 
linter-gcc 0.7.1 
print-code 0.7.1 
```

only my desktop has dis problem

**Comment by gloomydumber** [comment]
i just fixed by using another version of atom.
i changed https://github.com/atom/atom/releases/tag/v1.38.1 <- this version and
now i fixed..

**Comment by Crepe2002** [comment]
Uncaught Callback must be a function

fs.js:129
Hide Stack Trace
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (C:\Users\mures\.atom\packages\gpp-compiler\index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Right Bellow**

The error was thrown from the gpp-compiler package. This issue has already been reported.
