### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by gloomydumber** [kriscross07/atom-gpp-compiler#280]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Commands

```
  2x -0:18.9.0 gpp-compiler:compile (input.hidden-input)
     -0:13.7.0 editor:newline (input.hidden-input)
     -0:13.2.0 gpp-compiler:compile (input.hidden-input)
  3x -0:10.5.0 core:backspace (input.hidden-input)
     -0:08.5.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-file-icons 0.7.1 
gpp-compiler 3.0.7 
highlight-selected 0.16.0 
linter-gcc 0.7.1 
print-code 0.7.1 
```

i just fixed this problem by using another version of atom.
i changed https://github.com/atom/atom/releases/tag/v1.38.1 <- this version and
now i fixed..

**Comment by Vinit023** [comment]
Uncaught Callback must be a function #282
