### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by kirill89450** [kriscross07/atom-gpp-compiler#282]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

### Commands

```
     -0:57.2.0 snippets:expand (input.hidden-input)
     -0:57.2.0 editor:indent (input.hidden-input)
     -0:56 snippets:next-tab-stop (input.hidden-input)
     -0:56 snippets:expand (input.hidden-input)
     -0:56 editor:indent (input.hidden-input)
  2x -0:54.4.0 core:backspace (input.hidden-input)
     -0:53.6.0 snippets:next-tab-stop (input.hidden-input)
     -0:53.6.0 snippets:expand (input.hidden-input)
     -0:53.6.0 editor:indent (input.hidden-input)
  3x -0:51.6.0 core:backspace (input.hidden-input)
     -0:49.1.0 editor:newline (input.hidden-input)
  2x -0:39 core:backspace (input.hidden-input)
     -0:37.9.0 core:save (input.hidden-input)
     -0:37 gpp-compiler:compile (input.hidden-input)
 16x -0:26.4.0 core:undo (input.hidden-input)
     -0:18.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by glsscnnn** [comment]
Damn

**Comment by glsscnnn** [comment]
So I try to compile a simple strings program and it crashes what is this

**Comment by arrise** [comment]
I'm having the exact same issue.

**Comment by harjass** [comment]
I was having the same issue but agreeing to Xcode terms and agreements resolves it.

**Comment by psymbio** [comment]
Yep, same issue here

Edit: Tried returning a value in int main() and it seemed to resolve the problem. Maybe this wasn't explicitly happening.

**Comment by napovargas** [comment]
I am having the same issue when trying to compile a few simple programs.

**Comment by Moin-shadab** [comment]
wtf

**Comment by acryllect** [comment]
I have this issue and I'm not a great programmer, I'm just learning. I only have Xcode Command Line Tools installed.

**Comment by loganhutcheson** [comment]
To add, remember to include a '.cpp' file extension when saving your code. I received this error because I was saving my files without this extension and the compiler did not know what to do.

**Comment by kd4pba** [comment]
Ouch.  I hope this is resolved soon.

**Comment by kd4pba** [comment]
Thank you for the hard work fixing this.  One question remains.  How does one update this in Atom?  Are we simply waiting on an updated package to be built? Or do we need to pull this manually?

**Comment by Sidddharthh** [comment]
tf? this issue pops up in hello world? , fml

**Comment by marianyamukuru** [comment]
Make sure you have int main(){ }. This might solve your issue.
