### ISSUE TITLE
How do I fix the "Uncaught Callback must be a function" problem?

### ISSUE THREAD

**Issue by BlobbyCode** [kriscross07/atom-gpp-compiler#293]
So I have been trying to fix this a while. I am just starting out programming and I've got no luck so far, any help appreciated :)

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:129

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Commands

```
  2x -2:51.9.0 gpp-compiler:compile (input.hidden-input)
     -2:06.1.0 editor:newline (input.hidden-input)
     -2:05.8.0 core:paste (input.hidden-input)
 10x -2:04.4.0 gpp-compiler:compile (input.hidden-input)
     -1:42.1.0 core:confirm (input.hidden-input)
     -0:27.7.0 gpp-compiler:compile (input.hidden-input)
     -0:05.5.0 gpp-compiler:gdb (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by msi5322** [comment]
im having this same problem i put mingw on my path nit sure whats wrong

**Comment by kushagraag** [comment]
yeah..same problem with me, any one help please

**Comment by aum7** [comment]
same here ... 

thx for sharing

have fun,

simon
s love nia

**Comment by msi5322** [comment]
i reset my pc bc i had a issue editing my system variables it works now

**Comment by mksharifinia** [comment]
How do I fix that 
does need any liberary 

my system is Ubuntu 18.04

**Comment by KnifyMan** [comment]
Some help required

**Comment by ghost** [comment]
can you give me the code

**Comment by mksharifinia** [comment]
> can you give me the code

#include <glad/glad.h>
#include <GLFW/glfw3.h>
int main()
{
    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    //glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);

    return 0;
}

----------------------------------------------------------------------------------
:1:10: fatal error: glad/glad.h: No such file or directory
#include <glad/glad.h>
^~~~~
compilation terminated.





**I can't install glad**

**Comment by Giibnn** [comment]
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (C:\Users\Derek\.atom\packages\gpp-compiler\index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

**Comment by snehasisbasu** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught Callback must be a function

```
At fs.js:129

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Commands

```
     -0:30.4.0 application:open-folder (ul.list-inline.tab-bar.inset-panel)
     -0:25.9.0 application:open-file (atom-pane.pane.active)
     -0:18.7.0 gpp-compiler:compile (div.line)
```

### Non-Core Packages

```
gpp 0.4.3 
gpp-compiler 3.0.7 
```

**Comment by snehasisbasu** [comment]
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.43.0 x64
> **Electron**: 4.2.7
> **OS**: Microsoft Windows 10 Pro
> **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> 
> ### Stack Trace
> Uncaught Callback must be a function
> 
> ```
> At fs.js:129
> 
> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
>     at maybeCallback (fs.js:129:9)
>     at Object.writeFile (fs.js:1137:14)
>     at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
>     at ChildProcess.emit (events.js:182:13)
>     at maybeClose (internal/child_process.js:962:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
> ```
> 
> ### Commands
> ```
>      -0:30.4.0 application:open-folder (ul.list-inline.tab-bar.inset-panel)
>      -0:25.9.0 application:open-file (atom-pane.pane.active)
>      -0:18.7.0 gpp-compiler:compile (div.line)
> ```
> 
> ### Non-Core Packages
> ```
> gpp 0.4.3 
> gpp-compiler 3.0.7 
> ```

Visual Studio Code becomes a huge headache for c++ and now we cant run compile in Atom too

**Comment by snehasisbasu** [comment]
Did Anyone found any solution?

**Comment by Austin3dPrinting** [comment]
Also having the issue

**Comment by AveryJensen** [comment]
Having the same problem, but on macOS Catalina 10.15.2. I think it has something to do with a custom function in the code!!??

**Comment by AveryJensen** [comment]
Having the same problem on Catalina 10.15.2, but goes away when I don't define a custom function in code!!??

**Comment by snehasisbasu** [comment]
Mine Totally not working. But whats the use if u cant define a custom
function.

**Comment by snehasisbasu** [comment]
I dont know how but it got fixed.
