### ISSUE TITLE
Uncaught The "file" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by AnilDaal** [kriscross07/atom-gpp-compiler#313]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught The "file" argument must be of type string. Received type undefined

```
At internal/validators.js:125

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:404:3)
    at Object.spawn (child_process.js:537:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at HTMLLIElement.treeCompile (/packages/gpp-compiler/index.js:251:3)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:725135)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:733141)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -4:14.9.0 autocomplete-plus:confirm (input.hidden-input)
     -4:14.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -4:12.8.0 core:move-right (input.hidden-input)
     -4:10.1.0 editor:newline (input.hidden-input)
     -4:06.8.0 autocomplete-plus:confirm (input.hidden-input)
     -4:06.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -3:57.1.0 core:move-left (input.hidden-input)
  3x -3:55.5.0 core:backspace (input.hidden-input)
  5x -3:54.2.0 core:move-right (input.hidden-input)
  2x -3:49.8.0 core:move-down (input.hidden-input)
     -3:48.1.0 editor:newline (input.hidden-input)
     -3:46.5.0 autocomplete-plus:confirm (input.hidden-input)
     -3:46.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:42.2.0 autocomplete-plus:confirm (input.hidden-input)
     -3:42.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.9.0 gpp-compiler:tree-compile (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
file-icons 2.1.40 
gpp-compiler 3.0.7 
Hydrogen 2.14.1 
```

**Comment by lucakim27** [comment]
I have this issue

**Comment by musicalcircuit** [comment]
Also have this issue

**Comment by Feofano** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Linux Mint
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught The "file" argument must be of type string. Received type undefined

```
At internal/validators.js:125

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:404:3)
    at Object.spawn (child_process.js:537:38)
    at compile (/packages/gpp-compiler/index.js:274:31)
    at compileFile (/packages/gpp-compiler/index.js:216:5)
    at /packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1254747)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1250881)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -9:43.2.0 core:select-all (input.hidden-input)
     -9:42.6.0 core:paste (input.hidden-input)
     -9:26.4.0 core:select-all (input.hidden-input)
     -9:26 core:paste (input.hidden-input)
     -2:14.9.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-icons 2.1.40 
git-plus 8.7.1 
gpp-compiler 3.0.7 
Hydrogen 2.14.1 
ide-csharp 0.6.2 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
omnisharp-atom 0.31.2 
platformio-ide-terminal 2.10.0 
```

**Comment by Feofano** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Linux Mint
**Thrown From**: [omnisharp-atom](https://github.com/OmniSharp/omnisharp-atom) package 0.31.2


### Stack Trace

Failed to activate the omnisharp-atom package

```
At atom.grammars.startIdForScope is not a function

TypeError: atom.grammars.startIdForScope is not a function
    at grammarCb (/packages/omnisharp-atom/dist/omnisharp-atom.js:145:35)
    at arrayEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:516:11)
    at forEach (/packages/omnisharp-atom/node_modules/lodash/lodash.js:9342:14)
    at OmniSharpAtom.activate (/packages/omnisharp-atom/dist/omnisharp-atom.js:153:30)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3219604)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3219016)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3216626)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3218876)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3218819)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382452)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382068)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:331716)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382018)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381568)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:717298)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-icons 2.1.40 
git-plus 8.7.1 
gpp-compiler 3.0.7 
Hydrogen 2.14.1 
ide-csharp 0.6.2 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
omnisharp-atom 0.31.2 
platformio-ide-terminal 2.10.0 
```

**Comment by ninjaneek** [comment]
I was trina type up some js dunno if was correct:
strokeWeight(3);
stroke(57, 0, 214);
fill(0, 210, 247);

draw = function() {
    
    background(255, 255, 255);
    
    ellipse(200, 200, 30, 30);
    
};
but i ended up with this problem as well

**Comment by FixItYondu** [comment]
Is there a fix for this?
