### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by abdussametokutan** [kriscross07/atom-gpp-compiler#321]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Education
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:129

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Commands

```
     -4:41.1.0 editor:consolidate-selections (input.hidden-input)
     -4:41.1.0 core:cancel (input.hidden-input)
  4x -4:40.6.0 core:backspace (input.hidden-input)
     -4:39.9.0 editor:consolidate-selections (input.hidden-input)
     -4:39.9.0 core:cancel (input.hidden-input)
     -4:38.7.0 grammar-selector:show (input.hidden-input)
     -4:35.3.0 editor:select-line (div.tool-panel.tree-view)
  2x -4:10.4.0 grammar-selector:show (input.hidden-input)
     -0:36.1.0 tree-view:open-selected-entry-right (li.file.entry.list-item.selected)
     -0:30 core:save (input.hidden-input)
 10x -0:21.1.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
codeigniter 0.4.0 
file-icons 2.1.41 
gpp-compiler 3.0.7 
ide-c-cpp 0.1.0 
language-gpp 0.1.0 
script 3.26.0 
```

**Comment by sametoktn** [comment]
the problem has now fixed but i don't know how.
