### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by primesupra** [kriscross07/atom-gpp-compiler#322]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:137

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:917:14)
    at fs.stat (/packages/gpp-compiler/index.js:427:14)
    at FSReqWrap.oncomplete (fs.js:155:5)
```

### Commands

```
     -4:12.6.0 application:open-file (div.panels-item)
     -3:29.3.0 gpp-compiler:compile (input.hidden-input)
  8x -2:58.4.0 core:backspace (input.hidden-input)
     -2:55.6.0 core:save (input.hidden-input)
  2x -2:37.5.0 core:backspace (input.hidden-input)
  2x -2:29.1.0 editor:newline (input.hidden-input)
     -2:26.3.0 autocomplete-plus:confirm (input.hidden-input)
     -2:26.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 10x -2:23.2.0 core:backspace (input.hidden-input)
     -1:58.5.0 core:save (input.hidden-input)
     -1:56.8.0 gpp-compiler:compile (input.hidden-input)
     -0:56.9.0 core:save-as (input.hidden-input)
     -0:46.2.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by shanan-P** [comment]
I was having the same error, because I forget to close stop the already running program

**Comment by tzmod** [comment]
I fixed this by following this link https://github.com/gruntjs/grunt-contrib-jasmine/pull/262. I.e. changing `fs.unlink` to `fs.unlinkSync` at index.js line 427 and restarting Atom.
