### ISSUE TITLE
Uncaught TypeError: Callback must be a function

### ISSUE THREAD

**Issue by thatshadycodeboi** [kriscross07/atom-gpp-compiler#325]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

### Commands

```
     -5:54.9.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -5:30.4.0 core:backspace (input.hidden-input)
     -2:37.1.0 application:new-file (atom-pane.pane)
     -2:35.6.0 intentions:highlight (input.hidden-input)
     -2:35.1.0 core:save-as (input.hidden-input)
 11x -2:01.0 core:backspace (input.hidden-input)
     -1:50.4.0 editor:newline (input.hidden-input)
 12x -1:46 core:backspace (input.hidden-input)
  2x -1:31.8.0 editor:newline (input.hidden-input)
     -1:26.7.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 45x -1:19 core:backspace (input.hidden-input)
     -0:42.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
 24x -0:38 core:backspace (input.hidden-input)
     -0:12.4.0 intentions:highlight (input.hidden-input)
     -0:12.1.0 core:save (input.hidden-input)
     -0:09.3.0 gpp-compiler:compile (div.line)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-gdb-debugger 0.2.2 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.41 
gpp-compiler 3.0.7 
Hydrogen 2.14.1 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.1 
pigments 0.40.2 
script 3.26.0 
teletype 0.13.4 
```

**Comment by kleber-romano** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: KDE neon
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Socket.<anonymous> (internal/child_process.js:403:11)
    at Socket.emit (events.js:194:13)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
  5x -1:47.6.0 core:backspace (input.hidden-input)
 14x -1:27.8.0 core:delete (input.hidden-input)
  5x -1:19.7.0 core:move-up (input.hidden-input)
 11x -1:16.5.0 core:move-down (input.hidden-input)
     -1:12.2.0 intentions:highlight (input.hidden-input)
     -1:12 core:save (input.hidden-input)
     -1:09.9.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-blue-jeans-syntax 0.3.5 
atom-blue-jeans-ui 0.5.0 
atom-i18n 0.23.0 
atom-ide-ui 0.13.0 
busy-signal 2.0.1 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
logo-file-icons 1.13.0 
seti-icons 1.5.4 
```

**Comment by thatshadycodeboi** [comment]
u have the same problem?

**Comment by NILESH8757** [comment]
Did anyone resolve the issue
