### ISSUE TITLE
Uncaught TypeError: Callback must be a function

### ISSUE THREAD

**Issue by opantazis** [kriscross07/atom-gpp-compiler#328]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

### Commands

```
  4x -5:44.7.0 gpp-compiler:compile (input.hidden-input)
  2x -4:43.8.0 core:backspace (input.hidden-input)
     -4:19.6.0 core:move-left (input.hidden-input)
  3x -4:14.1.0 core:backspace (input.hidden-input)
  2x -4:00.7.0 gpp-compiler:compile (input.hidden-input)
     -2:10.8.0 core:paste (input.hidden-input)
     -2:07.1.0 gpp-compiler:compile (input.hidden-input)
     -1:36.8.0 settings-view:install-packages-and-themes (input.hidden-input)
 11x -0:10.6.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
ide-python 1.5.0 
script 3.26.0 
```

**Comment by cavecanem1** [comment]
Just follow the instructions in this tutorial:
1. https://www.youtube.com/watch?v=xwRoQ5GkwJI
And type the code exactly as the guy says, don´t use Atom´s typing suggestions. Also follow instructions in this tutorial:
2. https://www.youtube.com/watch?v=CxF-zEIjAfQ 

It should work, It did for me. Good luck and happy coding!
