### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by anshdholakia** [kriscross07/atom-gpp-compiler#330]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:129

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1137:14)
    at ChildProcess.child.on (/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Commands

```
     -4:07.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:06.1.0 core:backspace (input.hidden-input)
     -4:01.9.0 editor:newline (input.hidden-input)
  2x -4:01.2.0 core:backspace (input.hidden-input)
 21x -3:57.1.0 gpp-compiler:compile (input.hidden-input)
     -1:04.8.0 editor:newline (input.hidden-input)
     -0:58.7.0 gpp-compiler:compile (input.hidden-input)
     -0:49 core:move-right (input.hidden-input)
     -0:48.8.0 core:backspace (input.hidden-input)
     -0:47.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:45.8.0 core:undo (input.hidden-input)
  5x -0:43.6.0 core:backspace (input.hidden-input)
     -0:28.3.0 editor:newline (input.hidden-input)
     -0:27.1.0 core:move-right (input.hidden-input)
  5x -0:26.9.0 core:backspace (input.hidden-input)
     -0:12.9.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
g-code 1.1.0 
gpp-compiler 3.0.7 
```

**Comment by stefanosIoannou** [comment]
Same issue here

**Comment by youssefavx** [comment]
Same issue here on macos, not sure if this is my problem or not
