### ISSUE TITLE
Uncaught TypeError: Callback must be a function

### ISSUE THREAD

**Issue by Kitta-C** [kriscross07/atom-gpp-compiler#333]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

### Commands

```
     -8:28.7.0 core:backspace (input.hidden-input)
  2x -8:26.8.0 core:move-right (input.hidden-input)
  2x -8:25.4.0 core:backspace (input.hidden-input)
  2x -8:23.3.0 core:move-left (input.hidden-input)
  3x -8:14.4.0 core:move-up (input.hidden-input)
  9x -8:13.3.0 core:move-left (input.hidden-input)
  5x -8:07.5.0 core:move-right (input.hidden-input)
  2x -8:06.1.0 core:backspace (input.hidden-input)
     -8:03.5.0 core:move-right (input.hidden-input)
  3x -8:03.1.0 core:move-down (input.hidden-input)
 10x -8:01.4.0 core:move-right (input.hidden-input)
     -7:59.7.0 core:backspace (input.hidden-input)
  5x -7:58.1.0 core:move-left (input.hidden-input)
     -7:56 gpp-compiler:compile (input.hidden-input)
  4x -6:33.7.0 core:backspace (input.hidden-input)
     -0:18.3.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
autocomplete-clang 0.13.1 
busy-signal 2.0.1 
gpp-compiler 3.0.7 
ide-c-cpp 0.1.0 
intentions 1.1.5 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
```

**Comment by UltimateZCoder** [comment]
how do i fix this?

**Comment by terminal-guy** [comment]
> how do i fix this?

ADD THIS TO YOUR PATH THIS WILL FIX IT
HAPPY CODING :)

**Comment by souhibsaleh132** [comment]
> > how do i fix this?
> 
> ADD THIS TO YOUR PATH THIS WILL FIX IT
> HAPPY CODING :)

which one should i add ??

**Comment by terminal-guy** [comment]
> > > how do i fix this?
> > 
> > 
> > ADD THIS TO YOUR PATH THIS WILL FIX IT
> > HAPPY CODING :)
> 
> which one should i add ??

the .atom folder in your appdata folder.

**Comment by terminal-guy** [comment]
> > > how do i fix this?
> > 
> > 
> > ADD THIS TO YOUR PATH THIS WILL FIX IT
> > HAPPY CODING :)
> 
> which one should i add ??

this can be also a syntax error?

**Comment by terminal-guy** [comment]
> > > > how do i fix this?
> > > 
> > > 
> > > ADD THIS TO YOUR PATH THIS WILL FIX IT
> > > HAPPY CODING :)
> > 
> > 
> > which one should i add ??
> 
> this can be also a syntax error?

or which folder are you saving

**Comment by UltimateZCoder** [comment]
I added .atom to my path variable and im still getting the same error

**Comment by itslavanya** [comment]
Even I am facing the same problem 
please help with the steps

**Comment by itslavanya** [comment]
i got the solution 
just press "CTRL + F6" for compiling instead of just F6

**Comment by terminal-guy** [comment]
``

> I added .atom to my path variable and im still getting the same error

hey paste your code i will fix your problem there must be a syntax error or a link error  paste your code and i will reply to you within 24 hrs...:)

**Comment by terminal-guy** [comment]
> I added .atom to my path variable and im still getting the same error

you should save your file without spaces like this:

how_do_linkers_work.cpp

not like this:

how do linkers work.ccp

spaces are not allowed in saving the files in text editor instead of spaces use this 

" _ " or  "- " to separte the letters......

HAPPY CODING :)

**Comment by terminal-guy** [comment]
I have posted the varies solution for this issue in the gpp compilers issue
page go to that web page and see your issue and solve the problem
https://github.com/kriscross07/atom-gpp-compiler/issues/333

**Comment by ghost** [comment]
This is the error I'm getting
I appreciate any assistance 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

### Commands

```
     -3:17.1.0 gpp-compiler:compile (input.hidden-input)
     -2:18.8.0 command-palette:toggle (input.hidden-input)
     -2:08.5.0 core:confirm (input.hidden-input)
     -2:08.5.0 settings-view:install-packages-and-themes (input.hidden-input)
     -0:45.6.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by terminal-guy** [comment]
> This is the error I'm getting
> I appreciate any assistance
> 
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.48.0 x64
> **Electron**: 5.0.13
> **OS**: Microsoft Windows 10 Pro
> **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> 
> ### Stack Trace
> Uncaught TypeError: Callback must be a function
> 
> ```
> At fs.js:138
> 
> TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
>     at maybeCallback (fs.js:138:9)
>     at Object.writeFile (fs.js:1215:14)
>     at /packages/gpp-compiler/index.js:299:12)
>     at ChildProcess.emit (events.js:194:13)
>     at maybeClose (internal/child_process.js:998:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> ```
> 
> ### Commands
> ```
>      -3:17.1.0 gpp-compiler:compile (input.hidden-input)
>      -2:18.8.0 command-palette:toggle (input.hidden-input)
>      -2:08.5.0 core:confirm (input.hidden-input)
>      -2:08.5.0 settings-view:install-packages-and-themes (input.hidden-input)
>      -0:45.6.0 gpp-compiler:compile (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> ```
> gpp-compiler 3.0.7 
> ```
please post your code with it so we can help you there may be some kind of error like like linking error or compiler error

**Comment by terminal-guy** [comment]
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.48.0 x64
> **Electron**: 5.0.13
> **OS**: Unknown Windows version
> **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> 
> ### Stack Trace
> Uncaught TypeError: Callback must be a function
> 
> ```
> At fs.js:138
> 
> TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
>     at maybeCallback (fs.js:138:9)
>     at Object.writeFile (fs.js:1215:14)
>     at /packages/gpp-compiler/index.js:299:12)
>     at ChildProcess.emit (events.js:194:13)
>     at maybeClose (internal/child_process.js:998:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> ```
> 
> ### Commands
> ```
>      -8:28.7.0 core:backspace (input.hidden-input)
>   2x -8:26.8.0 core:move-right (input.hidden-input)
>   2x -8:25.4.0 core:backspace (input.hidden-input)
>   2x -8:23.3.0 core:move-left (input.hidden-input)
>   3x -8:14.4.0 core:move-up (input.hidden-input)
>   9x -8:13.3.0 core:move-left (input.hidden-input)
>   5x -8:07.5.0 core:move-right (input.hidden-input)
>   2x -8:06.1.0 core:backspace (input.hidden-input)
>      -8:03.5.0 core:move-right (input.hidden-input)
>   3x -8:03.1.0 core:move-down (input.hidden-input)
>  10x -8:01.4.0 core:move-right (input.hidden-input)
>      -7:59.7.0 core:backspace (input.hidden-input)
>   5x -7:58.1.0 core:move-left (input.hidden-input)
>      -7:56 gpp-compiler:compile (input.hidden-input)
>   4x -6:33.7.0 core:backspace (input.hidden-input)
>      -0:18.3.0 gpp-compiler:compile (input.hidden-input)
> ```
> 
> ### Non-Core Packages
> ```
> activate-power-mode 2.7.0 
> autocomplete-clang 0.13.1 
> busy-signal 2.0.1 
> gpp-compiler 3.0.7 
> ide-c-cpp 0.1.0 
> intentions 1.1.5 
> linter 2.3.1 
> linter-gcc 0.9.0 
> linter-ui-default 1.8.1 
> ```

please post your code with it so we can help you there may be some kind of error like like linking error or compiler error :)

**Comment by ghost** [comment]
> > [Enter steps to reproduce:]
> > 
> > 1. ...
> > 2. ...
> > 
> > **Atom**: 1.48.0 x64
> > **Electron**: 5.0.13
> > **OS**: Unknown Windows version
> > **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> > ### Stack Trace
> > Uncaught TypeError: Callback must be a function
> > ```
> > At fs.js:138
> > 
> > TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
> >     at maybeCallback (fs.js:138:9)
> >     at Object.writeFile (fs.js:1215:14)
> >     at /packages/gpp-compiler/index.js:299:12)
> >     at ChildProcess.emit (events.js:194:13)
> >     at maybeClose (internal/child_process.js:998:16)
> >     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> > ```
> > 
> > 
> > ### Commands
> > ```
> >      -8:28.7.0 core:backspace (input.hidden-input)
> >   2x -8:26.8.0 core:move-right (input.hidden-input)
> >   2x -8:25.4.0 core:backspace (input.hidden-input)
> >   2x -8:23.3.0 core:move-left (input.hidden-input)
> >   3x -8:14.4.0 core:move-up (input.hidden-input)
> >   9x -8:13.3.0 core:move-left (input.hidden-input)
> >   5x -8:07.5.0 core:move-right (input.hidden-input)
> >   2x -8:06.1.0 core:backspace (input.hidden-input)
> >      -8:03.5.0 core:move-right (input.hidden-input)
> >   3x -8:03.1.0 core:move-down (input.hidden-input)
> >  10x -8:01.4.0 core:move-right (input.hidden-input)
> >      -7:59.7.0 core:backspace (input.hidden-input)
> >   5x -7:58.1.0 core:move-left (input.hidden-input)
> >      -7:56 gpp-compiler:compile (input.hidden-input)
> >   4x -6:33.7.0 core:backspace (input.hidden-input)
> >      -0:18.3.0 gpp-compiler:compile (input.hidden-input)
> > ```
> > 
> > 
> > ### Non-Core Packages
> > ```
> > activate-power-mode 2.7.0 
> > autocomplete-clang 0.13.1 
> > busy-signal 2.0.1 
> > gpp-compiler 3.0.7 
> > ide-c-cpp 0.1.0 
> > intentions 1.1.5 
> > linter 2.3.1 
> > linter-gcc 0.9.0 
> > linter-ui-default 1.8.1 
> > ```
> 
> please post your code with it so we can help you there may be some kind of error like like linking error or compiler error :)

The thing is I'm trying it with the "Hello world" print command. I'm just trying to set it up on the machine, but it doesn't seem to like it.

**Comment by terminal-guy** [comment]
> > > [Enter steps to reproduce:]
> > > 
> > > 1. ...
> > > 2. ...
> > > 
> > > **Atom**: 1.48.0 x64
> > > **Electron**: 5.0.13
> > > **OS**: Unknown Windows version
> > > **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> > > ### Stack Trace
> > > Uncaught TypeError: Callback must be a function
> > > ```
> > > At fs.js:138
> > > 
> > > TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
> > >     at maybeCallback (fs.js:138:9)
> > >     at Object.writeFile (fs.js:1215:14)
> > >     at /packages/gpp-compiler/index.js:299:12)
> > >     at ChildProcess.emit (events.js:194:13)
> > >     at maybeClose (internal/child_process.js:998:16)
> > >     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> > > ```
> > > 
> > > 
> > > ### Commands
> > > ```
> > >      -8:28.7.0 core:backspace (input.hidden-input)
> > >   2x -8:26.8.0 core:move-right (input.hidden-input)
> > >   2x -8:25.4.0 core:backspace (input.hidden-input)
> > >   2x -8:23.3.0 core:move-left (input.hidden-input)
> > >   3x -8:14.4.0 core:move-up (input.hidden-input)
> > >   9x -8:13.3.0 core:move-left (input.hidden-input)
> > >   5x -8:07.5.0 core:move-right (input.hidden-input)
> > >   2x -8:06.1.0 core:backspace (input.hidden-input)
> > >      -8:03.5.0 core:move-right (input.hidden-input)
> > >   3x -8:03.1.0 core:move-down (input.hidden-input)
> > >  10x -8:01.4.0 core:move-right (input.hidden-input)
> > >      -7:59.7.0 core:backspace (input.hidden-input)
> > >   5x -7:58.1.0 core:move-left (input.hidden-input)
> > >      -7:56 gpp-compiler:compile (input.hidden-input)
> > >   4x -6:33.7.0 core:backspace (input.hidden-input)
> > >      -0:18.3.0 gpp-compiler:compile (input.hidden-input)
> > > ```
> > > 
> > > 
> > > ### Non-Core Packages
> > > ```
> > > activate-power-mode 2.7.0 
> > > autocomplete-clang 0.13.1 
> > > busy-signal 2.0.1 
> > > gpp-compiler 3.0.7 
> > > ide-c-cpp 0.1.0 
> > > intentions 1.1.5 
> > > linter 2.3.1 
> > > linter-gcc 0.9.0 
> > > linter-ui-default 1.8.1 
> > > ```
> > 
> > 
> > please post your code with it so we can help you there may be some kind of error like like linking error or compiler error :)
> 
> The thing is I'm trying it with the "Hello world" print command. I'm just trying to set it up on the machine, but it doesn't seem to like it.

hello do you understand 

> > > [Enter steps to reproduce:]
> > > 
> > > 1. ...
> > > 2. ...
> > > 
> > > **Atom**: 1.48.0 x64
> > > **Electron**: 5.0.13
> > > **OS**: Unknown Windows version
> > > **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> > > ### Stack Trace
> > > Uncaught TypeError: Callback must be a function
> > > ```
> > > At fs.js:138
> > > 
> > > TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
> > >     at maybeCallback (fs.js:138:9)
> > >     at Object.writeFile (fs.js:1215:14)
> > >     at /packages/gpp-compiler/index.js:299:12)
> > >     at ChildProcess.emit (events.js:194:13)
> > >     at maybeClose (internal/child_process.js:998:16)
> > >     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> > > ```
> > > 
> > > 
> > > ### Commands
> > > ```
> > >      -8:28.7.0 core:backspace (input.hidden-input)
> > >   2x -8:26.8.0 core:move-right (input.hidden-input)
> > >   2x -8:25.4.0 core:backspace (input.hidden-input)
> > >   2x -8:23.3.0 core:move-left (input.hidden-input)
> > >   3x -8:14.4.0 core:move-up (input.hidden-input)
> > >   9x -8:13.3.0 core:move-left (input.hidden-input)
> > >   5x -8:07.5.0 core:move-right (input.hidden-input)
> > >   2x -8:06.1.0 core:backspace (input.hidden-input)
> > >      -8:03.5.0 core:move-right (input.hidden-input)
> > >   3x -8:03.1.0 core:move-down (input.hidden-input)
> > >  10x -8:01.4.0 core:move-right (input.hidden-input)
> > >      -7:59.7.0 core:backspace (input.hidden-input)
> > >   5x -7:58.1.0 core:move-left (input.hidden-input)
> > >      -7:56 gpp-compiler:compile (input.hidden-input)
> > >   4x -6:33.7.0 core:backspace (input.hidden-input)
> > >      -0:18.3.0 gpp-compiler:compile (input.hidden-input)
> > > ```
> > > 
> > > 
> > > ### Non-Core Packages
> > > ```
> > > activate-power-mode 2.7.0 
> > > autocomplete-clang 0.13.1 
> > > busy-signal 2.0.1 
> > > gpp-compiler 3.0.7 
> > > ide-c-cpp 0.1.0 
> > > intentions 1.1.5 
> > > linter 2.3.1 
> > > linter-gcc 0.9.0 
> > > linter-ui-default 1.8.1 
> > > ```
> > 
> > 
> > please post your code with it so we can help you there may be some kind of error like like linking error or compiler error :)
> 
> The thing is I'm trying it with the "Hello world" print command. I'm just trying to set it up on the machine, but it doesn't seem to like it.

i have posted many solution to your problems in this page please go and check that out

**Comment by terminal-guy** [comment]
> > > [Enter steps to reproduce:]
> > > 
> > > 1. ...
> > > 2. ...
> > > 
> > > **Atom**: 1.48.0 x64
> > > **Electron**: 5.0.13
> > > **OS**: Unknown Windows version
> > > **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> > > ### Stack Trace
> > > Uncaught TypeError: Callback must be a function
> > > ```
> > > At fs.js:138
> > > 
> > > TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
> > >     at maybeCallback (fs.js:138:9)
> > >     at Object.writeFile (fs.js:1215:14)
> > >     at /packages/gpp-compiler/index.js:299:12)
> > >     at ChildProcess.emit (events.js:194:13)
> > >     at maybeClose (internal/child_process.js:998:16)
> > >     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
> > > ```
> > > 
> > > 
> > > ### Commands
> > > ```
> > >      -8:28.7.0 core:backspace (input.hidden-input)
> > >   2x -8:26.8.0 core:move-right (input.hidden-input)
> > >   2x -8:25.4.0 core:backspace (input.hidden-input)
> > >   2x -8:23.3.0 core:move-left (input.hidden-input)
> > >   3x -8:14.4.0 core:move-up (input.hidden-input)
> > >   9x -8:13.3.0 core:move-left (input.hidden-input)
> > >   5x -8:07.5.0 core:move-right (input.hidden-input)
> > >   2x -8:06.1.0 core:backspace (input.hidden-input)
> > >      -8:03.5.0 core:move-right (input.hidden-input)
> > >   3x -8:03.1.0 core:move-down (input.hidden-input)
> > >  10x -8:01.4.0 core:move-right (input.hidden-input)
> > >      -7:59.7.0 core:backspace (input.hidden-input)
> > >   5x -7:58.1.0 core:move-left (input.hidden-input)
> > >      -7:56 gpp-compiler:compile (input.hidden-input)
> > >   4x -6:33.7.0 core:backspace (input.hidden-input)
> > >      -0:18.3.0 gpp-compiler:compile (input.hidden-input)
> > > ```
> > > 
> > > 
> > > ### Non-Core Packages
> > > ```
> > > activate-power-mode 2.7.0 
> > > autocomplete-clang 0.13.1 
> > > busy-signal 2.0.1 
> > > gpp-compiler 3.0.7 
> > > ide-c-cpp 0.1.0 
> > > intentions 1.1.5 
> > > linter 2.3.1 
> > > linter-gcc 0.9.0 
> > > linter-ui-default 1.8.1 
> > > ```
> > 
> > 
> > please post your code with it so we can help you there may be some kind of error like like linking error or compiler error :)
> 
> The thing is I'm trying it with the "Hello world" print command. I'm just trying to set it up on the machine, but it doesn't seem to like it.

do you install minGW compiler for c++ in your system

if you did not install minGW  gpp compiler will not work on your system...


if you want to install it this is the video:
https://www.youtube.com/watch?v=zaokK25DITo

**Comment by terminal-guy** [comment]
If you have any issue in gpp-compiler send me a mail at:
            vishaladhithya19@gmail.com
   
                            or 
ask in instragram:

            https://www.instagram.com/vishal__b05/?hl=en

**Comment by terminal-guy** [comment]
If you have any issue in gpp-compiler send me a mail at:
            vishaladhithya19@gmail.com
   
                            or 
ask in instragram:

            https://www.instagram.com/vishal__b05/?hl=en

**Comment by ghost** [comment]
> If you have any issue in gpp-compiler send me a mail at:
> [vishaladhithya19@gmail.com](mailto:vishaladhithya19@gmail.com)
> 
> ```
>                         or 
> ```
> 
> ask in instragram:
> 
> ```
>         https://www.instagram.com/vishal__b05/?hl=en
> ```

Cheers, mate. I didn't figure out exactly where the issue was, but it is working fine after a complete shutdown.
Quite sure about my installation steps since I followed the video you shared. Thanks for your kind support and happy coding :)

**Comment by terminal-guy** [comment]
> > If you have any issue in gpp-compiler send me a mail at:
> > [vishaladhithya19@gmail.com](mailto:vishaladhithya19@gmail.com)
> > ```
> >                         or 
> > ```
> > 
> > 
> > ask in instragram:
> > ```
> >         https://www.instagram.com/vishal__b05/?hl=en
> > ```
> 
> Cheers, mate. I didn't figure out exactly where the issue was, but it is working fine after a complete shutdown.
> Quite sure about my installation steps since I followed the video you shared. Thanks for your kind support and happy coding :)

You are welcome

**Comment by kezjo** [comment]
> how do i fix this?

add _**using namespace std;**_ in your code. It works for me :)

**Comment by someshfengde** [comment]
I am getting same error and added the environment variable done restarting running as administrator but nothing is working with atom

**Comment by someshfengde** [comment]
fs.js:138
Hide Stack Trace
TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at ChildProcess.<anonymous> (C:\Users\ramesh\.atom\packages\gpp-compiler\index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
here is the error

**Comment by vooop-binary** [comment]
> [Enter steps to reproduce:]

**Comment by kermzyx** [comment]
> how do i fix this?

I had the same issue even with MinGW compiler which is added to my PATH. Just delete gpp-compiler, then go to **config** and delete everything refers to gpp-compiler and then install it again. It worked for me. Maybe I had such problem because of conflicting python runner and cpp runner which had same shortcuts.

**Comment by renanlarrieu** [comment]
Help! I'm getting error.

**Comment by RhuthuHegde** [comment]
> > If you have any issue in gpp-compiler send me a mail at:
> > [vishaladhithya19@gmail.com](mailto:vishaladhithya19@gmail.com)
> > ```
> >                         or 
> > ```
> > 
> > 
> > ask in instragram:
> > ```
> >         https://www.instagram.com/vishal__b05/?hl=en
> > ```
> 
> Cheers, mate. I didn't figure out exactly where the issue was, but it is working fine after a complete shutdown.
> Quite sure about my installation steps since I followed the video you shared. Thanks for your kind support and happy coding :)

**Comment by RhuthuHegde** [comment]
Dude even I am facing a similar problem!
Did you add the atom path in the environment variables? is it mandatory for it to work??

**Comment by renanlarrieu** [comment]
Hi bro, I have no solutions to gpp compiler so far. However, I downloaded
the package called Hydrogen and it's working well, you should try it.

Regards,

Att,
Renan Larrieu de Abreu Mourão

Graduação em Engenharia Elétrica - UERJ - 5° período
