### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by Steam-Bear** [kriscross07/atom-gpp-compiler#349]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0-nightly3 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Education
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
     -3:05.5.0 gpp-compiler:compile (input.hidden-input)
     -1:20.7.0 core:save-as (input.hidden-input)
     -0:51.7.0 core:copy (input.hidden-input)
     -0:49.7.0 core:paste (input.hidden-input)
     -0:47.3.0 core:save (input.hidden-input)
     -0:45.1.0 editor:newline (input.hidden-input)
  6x -0:41.2.0 core:backspace (input.hidden-input)
  2x -0:25.1.0 core:move-right (input.hidden-input)
     -0:24.5.0 core:move-left (input.hidden-input)
  3x -0:23.1.0 editor:newline (input.hidden-input)
     -0:08.2.0 core:save (input.hidden-input)
     -0:07.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-java-decompiler 0.1.2 
autocomplete 0.47.0 
busy 0.7.0 
gpp-compiler 3.0.7 
ide-java 0.9.0 
java-classpath-registry 0.4.0 
java-import-wiz 0.5.0 
java-plus 0.1.0 
script 3.26.0 
teletype 0.13.4 
```

**Comment by Steam-Bear** [comment]
I fixed this issue by running everything in base Atom (I was using Atom Nightly)
