### ISSUE TITLE
Uncaught TypeError: Callback must be a function

### ISSUE THREAD

**Issue by DhananjayPorwal** [kriscross07/atom-gpp-compiler#350]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:138

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:138:9)
    at Object.writeFile (fs.js:1215:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:194:13)
    at maybeClose (internal/child_process.js:998:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

### Commands

```
     -0:56.4.0 application:open-file (input.hidden-input)
  9x -0:37.4.0 gpp-compiler:compile (input.hidden-input)
     -0:23.7.0 core:move-right (input.hidden-input)
  4x -0:23.2.0 core:backspace (input.hidden-input)
  2x -0:21 gpp-compiler:compile (input.hidden-input)
  2x -0:09.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by markabbott867** [comment]
I've just started my 2nd at Uni and I'm the only one using MACOS system.
Having the same problem...
I've checked to see if my Xcode command tools are in place and they are. 
but i'm not too sure if they are linked to atom...

Need to get this working as I have to get on with my studys.

**Comment by DerCringe** [comment]
HELP it didnt work !
Need a answer on this Question !!

**Comment by Nithi1710** [comment]
![Screenshot_20200925_122504](https://user-images.githubusercontent.com/58131526/94236133-52bc4180-ff2a-11ea-9bf6-4195e40fc858.png)
please help me to fix this error.everytime when i compile ,i have this error

**Comment by noideaatall0** [comment]
Did you installed MinGw and added path to environmental variables?

**Comment by DhananjayPorwal** [comment]
Yes, I installed MinGw and added it to the path, but I face the
same problem you are facing. After i tried alot, i give up. Later on I
install Visual Studio Code and it worked fine.

**Comment by ansisg** [comment]
I had this error show up once but the code still compiled, havent ever seen it afterwards.

**Comment by Mahesh-github1** [comment]
> Did you installed MinGw and added path to environmental variables?

yes i am also facing the same problem

**Comment by Mahesh-github1** [comment]
please help mee

**Comment by madonuko** [comment]
Problem also occurs on Linux. g++ and gcc installed

**Comment by frady95** [comment]
I had the same problem, and it resolved after I updated my version of MinGW. If you follow <a href="http://www.mingw.org/wiki/Getting_Started" target="_blank">this guide</a> it will be a lot easier to install it properly.

**Comment by RahulNegi123** [comment]
![Screen Shot 10-10-20 at 06 03 PM](https://user-images.githubusercontent.com/54587454/95655193-2f48e780-0b23-11eb-996a-8bf66af3d35f.JPG)
do anybody know, how can i keep this error notifications for longer...it just diappera too early, before i am able to read them properly...please help ......

**Comment by frady95** [comment]
> ![Screen Shot 10-10-20 at 06 03 PM](https://user-images.githubusercontent.com/54587454/95655193-2f48e780-0b23-11eb-996a-8bf66af3d35f.JPG)
> do anybody know, how can i keep this error notifications for longer...it just diappera too early, before i am able to read them properly...please help ......

just double click on one notification to keep it open. You can keep just one notification at a time though.

**Comment by RahulNegi123** [comment]
@frady95  thanks for replying...is there any alternative (like any package, plugin ) something like that for a proper error showing functionality and not these notifications.

**Comment by frady95** [comment]
@RahulNegi123 not that I know of, sorry. Judging from the error, it's probably a callback function that's missing from the libraries. If you have installed MinGw just now and you are on windows, check if it's up to date and if the folders are properly indicated in the path. If you need help, I linked a guide in my first comment. Maybe that can help you.

**Comment by RahulNegi123** [comment]
@frady95  ok thanks, the error was intentional, i just wanted to know if error notifications can last longer...i'll just stick to vscode i guess. thanks
