### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by aman-7299** [kriscross07/atom-gpp-compiler#358]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
     -8:52.6.0 tree-view:remove (span.name.icon.icon-file-text)
     -7:51.4.0 core:backspace (input.hidden-input)
  3x -7:43.1.0 editor:newline (input.hidden-input)
  3x -7:24.8.0 core:backspace (input.hidden-input)
  3x -7:17.6.0 editor:newline (input.hidden-input)
  4x -6:33.4.0 core:backspace (input.hidden-input)
     -5:15.3.0 editor:newline (input.hidden-input)
     -5:09.2.0 core:backspace (input.hidden-input)
     -4:47.2.0 core:save (input.hidden-input)
  2x -4:36.8.0 gpp-compiler:compile (input.hidden-input)
     -3:10.6.0 tree-view:remove (span.name.icon.icon-file-text)
     -3:04.7.0 gpp-compiler:compile (div.line)
     -0:34.1.0 core:paste (input.hidden-input)
     -0:27.2.0 core:save (input.hidden-input)
     -0:17.4.0 gpp-compiler:compile (div.line)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by theyoungwriter-tk** [comment]
Yes, I get the same error too.

**Comment by Andreto** [comment]
**+1 (Solved)** 
Make sure that you have a return statement in your main loop. This resolved the issue for me.

**Comment by ghost** [comment]
i too got this error ,how can i solve this?

**Comment by TinkerWizard** [comment]
Yeah, @Andreto i cant solve this error.... How to kick this.?. i tried your way ,doesnt work

**Comment by Andreto** [comment]
Maybe try installing MinGW with the MinGW setup tool following this tutorial. https://www.youtube.com/watch?v=xwRoQ5GkwJI

**Comment by TinkerWizard** [comment]
@Andreto  ummm,..yeah...but i have to tell,i just installed mingw!!!!........ Is this issue is for everyone?

**Comment by Andreto** [comment]
@starksiv  I don't know if I can help you then. Maybe check these https://github.com/kriscross07/atom-gpp-compiler/pull/285, https://github.com/kriscross07/atom-gpp-compiler/issues/319. They claim that they have solved the issue.

**Comment by TinkerWizard** [comment]
@Andreto thank you so much!!!! ☻

**Comment by Ilbekko** [comment]
how do how do i get xcode to work with atom if I'm on a Mac?

**Comment by RichardMorris** [comment]
I think this error is caused by issue 284 https://github.com/kriscross07/atom-gpp-compiler/issues/284. Changing fs.writeFile(...) to fs.writeFileSync(...) on line 299 and changing fs.unlink(...) to fs.unlinkSync(...) on line 427 of index.js, both successfully writes the compiling_error.txt file and makes this other error go away.

**Comment by srai86825** [comment]
helppppp;;;; how to fix this

**Comment by Mystogan-0** [comment]
Same error, I tried reinstalling MinGW but it didn't help. Does anyone know how to solve this??

**Comment by RichardMorris** [comment]
> Same error, I tried reinstalling MinGW but it didn't help. Does anyone know how to solve this??

Do you have a stack trace, (see Developer console)

If top of the stack trace is

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)

then see my fix a couple of comments above.
