### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by zFireBlaze** [kriscross07/atom-gpp-compiler#361]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
     -9:28.7.0 symbols-view:go-to-declaration (div.highlights)
     -9:22.9.0 github:view-staged-changes-for-current-file (div.highlights)
 14x -1:10.5.0 gpp-compiler:compile (div.highlights)
     -0:30.1.0 find-and-replace:find-next (input.hidden-input)
     -0:30.1.0 core:move-up (input.hidden-input)
     -0:30.1.0 core:move-left (input.hidden-input)
     -0:29.9.0 core:move-right (input.hidden-input)
     -0:29.9.0 bookmarks:jump-to-next-bookmark (input.hidden-input)
     -0:29.9.0 find-and-replace:find-next (input.hidden-input)
     -0:29.9.0 core:move-up (input.hidden-input)
     -0:29.9.0 core:move-left (input.hidden-input)
     -0:13.4.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by zFireBlaze** [comment]
When I run with gcc compiler it gives me an error with a g ++ file.
I made sure it was inside the bin folder, however it doesn't work

**Comment by deepansharya1111** [comment]
Were you able to solve this error? I am also getting this error while trying to run my .c code in Atom editor
