### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by Zhink161** [kriscross07/atom-gpp-compiler#366]
When I press F5 or run and compile my file, it doesn't work. 
I use C++ and this is the code that I use:

#include <iostream>
using namespace std;

int main() {
    cout << "Hello World";
    return 0;
}

I consider the tabs in the code.
I tried many things but nothing seems to work. I will use another Editor now, but maybe someone can help me with this so I can use C++ in Atom.

**Comment by NullaFacente04** [comment]
hi @FreddyGAlvaro, you just forgot to write <iostream> near #include
it's something like this:

#include <iostream>
using namespace std;

int main() {
cout << "Hello World";
return 0;
}

**Comment by ghost** [comment]
hi @FreddyGAlvaro, maybe you just forgot to write `<iostream>` near `#include`.
it's something like this:
`#include  < iostream>
using namespace std;

int main() {
cout << "Hello World";
return 0;
}`
just, don't add the space before the "<"; I had to cause GitHub will hides it if I don't.

**Comment by Xamhy** [comment]
@NullaFacente04 I got my code just as you said, but it doesnt work, I got the same issue that Freddy, but Im new at coding so I dont know what to do lmao, I already added the compiler on the path and everything seems to be ok, I dont know why this is happening

**Comment by ghost** [comment]
Can you paste your code here? So I can check it

**Comment by Xamhy** [comment]
#include <iostream>
using namespace std;
int main(){
cout << "Hello World" << endl;
return 0;
}
I edited it, and now the issue has gone but a new one has appeared in a cmd window that shows up 
![image](https://user-images.githubusercontent.com/78188533/106239196-0bcfa880-61b7-11eb-8f0c-cfcf68eebb2d.png)

**Comment by NinoCourtecuisse** [comment]
@FreddyGAlvaro I had the same error. I have updated mingw and now it's working. Here is the page that helps me updating from cmd : https://stackoverflow.com/questions/9865319/how-to-update-gcc-in-mingw-on-windows

**Comment by freshefisch** [comment]
I think I know the solution to your problem @Xamhy . You probably named your project "Hola World" or something like that. The important thing is that when you hit f5 it somehow only copies the first word from the name of your script. So **try replacing the " " with an "_"** _in your file name_ or just only one word (smth like "Test", just to see, or "Hola_World") = It shouldn't contain a blank.

**Comment by Xamhy** [comment]
@gurke12 You're awesome, thanks, now finally I can start to learn lol 
![image](https://user-images.githubusercontent.com/78188533/106321024-8dabea00-6228-11eb-9d93-f3e091412b33.png)

**Comment by Zhink161** [comment]
@NullaFacente04 

It still doesn't work

**Comment by ghost** [comment]
@FreddyGAlvaro I copied your code on my Atom and I can compile and run it, maybe it's a file's problem.
Try to copied it into an another one.

**Comment by Zhink161** [comment]
I already changed the script of the index.js, maybe there I did something wrong.


This is what I get when the issue comes up:
TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at ChildProcess.<anonymous> `(C:\Users\user\.atom\packages\gpp-compiler\index.js:299:12)`
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

It's at `(C:\Users\"my name"\.atom\packages\gpp-compiler\index.js:299:12)`


@NullaFacente04 what do mean to copy into an another one? What another one?
Edit: oh you mean "try to copy it into another file". Okay I do that

**Comment by Zhink161** [comment]
Trying to copy it into another file and compile and run it doesn't work

**Comment by rudolphos** [comment]
Same problem. I thought spaces in path might be a problem, but then I placed it on desktop and having the same problem.
I have Mingw-w64 installed.

```
TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at ChildProcess.<anonymous> (C:\Users\...\.atom\packages\gpp-compiler\index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

![image](https://user-images.githubusercontent.com/4366810/107364983-dabf7400-6ae4-11eb-910b-ed0d0c85a0c0.png)

**Comment by alexxrico** [comment]
@FreddyGAlvaro 
Hi, I don't know if we have the same error since I get something similar to you, but I think it is because there is a space in the username folder. The problem is, I don't know how to select that. :(

I don't know English, I use a translator.

**Comment by manishrnl** [comment]
> When I press F5 or run and compile my file, it doesn't work.
> I use C++ and this is the code that I use:
> 
> #include
> using namespace std;
> 
> int main() {
> cout << "Hello World";
> return 0;
> }
> 
> I consider the tabs in the code.
> I tried many things but nothing seems to work. I will use another Editor now, but maybe someone can help me with this so I can use C++ in Atom.

install gpp compiler and then compile it.it will give you output

**Comment by abkisssb** [comment]
@manishrnl 

if you are on windows follow this instruction and install gpp compiler etc.. 
https://www.youtube.com/watch?v=sXW2VLrQ3Bs

**Comment by intersetinglab21** [comment]
> When I press F5 or run and compile my file, it doesn't work.
> I use C++ and this is the code that I use:
> 
> #include
> using namespace std;
> 
> int main() {
> cout << "Hello World";
> return 0;
> }
> 
> I consider the tabs in the code.
> I tried many things but nothing seems to work. I will use another Editor now, but maybe someone can help me with this so I can use C++ in Atom.
just add the header file <iostream>
#include<iostream>
using namespace std;
int main(){
cout<<"Hello World";
}
