### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ccs1021** [kriscross07/atom-gpp-compiler#367]
Trying to go through "Discovering modern C++" and the first command is,

#include <iostream>
int main ()
{
  std::cout << “The answer to the Ultimate Question of Life,\n”
            << “the Universe, and Everything is:”
            << std::endl << 6 * 7 << std::endl;

return 0;
}

I type this but I get an error 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
     -5:21.4.0 core:copy (input.hidden-input)
     -4:25.2.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  2x -4:13.4.0 gpp-compiler:compile (input.hidden-input)
     -0:20.6.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

if anyone knows what this means please let me know! I am brand new to c++ by the way.

**Comment by HemanthSai7** [comment]
u need to mention #include<iostream>
