### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by jessyuan24** [kriscross07/atom-gpp-compiler#37]
path.js:7
Hide Stack Trace
TypeError: Path must be a string. Received null
  at assertPath (path.js:7:11)
  at Object.parse (path.js:1536:5)
  at HTMLLIElement.treeCompile (/Users/JessYuan/.atom/packages/gpp-compiler/index.js:246:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1110:28)
  at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:342:25)
  at emitThree (events.js:110:13)
  at EventEmitter.emit (events.js:188:7)

**Comment by PoVa** [comment]
Is the file you're trying to compile saved?

**Comment by jessyuan24** [comment]
yes.

**Comment by kriscross07** [comment]
Does disabling all other plugins, restarting atom and trying again work? If not, enable gpp-compiler's `Debug mode` in settings.
