### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by AGuerrero123** [kriscross07/atom-gpp-compiler#371]
I am new to programming and atom. So, I don't have a lot of knowledge on how to setup atom. I might have missed a step, but I am trying to compile and run my code but I would get an, "Uncaught TypeError.." Looked through other submission, but none of the advise has work for me so far.

Any help would be greatly appreciated!

**I am using C++ & Code below :**

```
#include <iostream>
using namespace std;

int main ()
  {
    cout << "Hello World" << endl;
    return 0;
  }

```

**Error Displayed:**

fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at ChildProcess.<anonymous> (/Users/amandaguerrero/.atom/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)

Atom: 1.54.0 x64
Electron: 6.1.12
OS: macOS Big Sur
Thrown From: gpp-compiler package 3.0.7

**Comment by AGuerrero123** [comment]
I have seem to figure out my problem. When creating a new file using C program. I had to save file with either .c or .cpp in order to compile. 

Found solution in submission #364 by VedanshSharma0412
