### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by kevingjoni** [kriscross07/atom-gpp-compiler#376]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:142

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:142:9)
    at Object.writeFile (fs.js:1175:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
  2x -0:31.1.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
ide-c-cpp 0.1.0 
```

**Comment by Viraj-M** [comment]
Yeah  guys help this guy and me IT SO IRITATING

**Comment by TheLuke02** [comment]
I have the same issue

**Comment by Harumaru75** [comment]
Yes, having the same issue. Can someone walk me through the process of changing PATH to include the gpp compiler? I think that's where my issue lies.

**Comment by SAYAN444-CHAOS** [comment]
yes i have also face the same problem

**Comment by Viraj-M** [comment]
Bruh why is no one commenting anything about this?

**Comment by Viraj-M** [comment]
like the solution or anything

**Comment by 0pk0** [comment]
anyone who fixed this ?

**Comment by SarahX** [comment]
I also have the same problem

**Comment by Viraj-M** [comment]
BRUH i tried changing my path niothing

**Comment by Viraj-M** [comment]
i now started using visual studio code if u cant solve this problem try switching over to visual studio code like the themes are also available and extensions are the same so yeah

**Comment by Viraj-M** [comment]
oh yeah and c programs were running but not in atom

**Comment by Harumaru75** [comment]
Visual Studio is WAAAAAAAAY better.

**Comment by JunK4i** [comment]
My problem was solved when I stopped my existing running program. Make sure u close all other terminals.

**Comment by Viraj-M** [comment]
nope dosent work for me JunK4i

**Comment by beniodaisuke** [comment]
初めまして　C＋＋を勉強中のものです。同じエラーが出てコンパイルできません。因みに　インストールしたpackagesは、atom-beautify  linter-gcc  japanese-menu  gpp-compilerです。解決方法や設定方法など教えて頂きたいです。

**Comment by akramex-dz** [comment]
Any concreat solution?

**Comment by SarahX** [comment]
有没有人有办法解决吗
即使您更改PATH，仍然无法正常工作

**Comment by SasidharanGS** [comment]
Please refer this thread for instructions on linking the math library:
https://github.com/kriscross07/atom-gpp-compiler/issues/100

**Comment by Fitap** [comment]
> Please refer this thread for instructions on linking the math library:
> #100

Thanks a lot.
I have same issue and this solved for me.

**Comment by RakibOFC** [comment]
I have solved my problem.
Open Linux terminal (Ctrl+Alt+T) and enter: `sudo apt install gcc g++`
(Y/n): Y

**Full description:**
### Linux

The GNU Compiler Collection may come with your distribution. Run which gcc g++ to find out.

If that command does not output

/usr/bin/gcc
/usr/bin/g++
you will need to install it.

For RHEL-based distros, run `sudo dnf install gcc gcc-c++`

For Debian-based distros, run `sudo apt install gcc g++`

For Arch-based distros, run `sudo pacman -S gcc`

**Comment by Supragy352** [comment]
Ok so I've got a solution.
Basically, the C and C++ compilers are different (obviously), and so far only 3 types of reasons might be causing this error. Try and follow the steps and I hope the thing starts working.
1. Check your system path for errors. It is suposed to have "C:\Program Files\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin".
2. The function Atom is trying to call does not exist in the compiler you are invoking, So. make sure that in the package settings, the C compiler is set to "gcc" and the C++ compiler is set to "g++".
3. Try reinstalling MingW compiler.

**Comment by yashyadav711** [comment]
Installing both gpp-compiler and cpp-compiler solved the problem for me.

**Comment by mrityunjai01** [comment]
Settings > Packages > View Code under gpp compiler

In the file index.js 
line 299 changed to
```
fs.writeFile(path.join(info.dir, "compiling_error.txt"), (err) => {});
```
line 427 changed to
```
fs.unlink(path.join(info.dir, "compiling_error.txt"), (err) => {});
```

Then disabling and re-enabling the package from settings solved the issue.
