### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by marqueznelju** [kriscross07/atom-gpp-compiler#396]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 11 Home Single Language
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:135

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

### Commands

```
     -1:31.8.0 intentions:highlight (input.hidden-input)
     -1:31.6.0 core:paste (input.hidden-input)
 53x -1:20.2.0 core:move-up (input.hidden-input)
  3x -1:14.6.0 editor:newline (input.hidden-input)
  3x -1:13.1.0 core:move-up (input.hidden-input)
     -1:05.2.0 core:move-down (input.hidden-input)
  2x -1:04.4.0 core:move-left (input.hidden-input)
     -1:00.4.0 core:move-right (input.hidden-input)
     -0:59.5.0 editor:newline (input.hidden-input)
 32x -0:50.8.0 core:move-down (input.hidden-input)
     -0:44.5.0 intentions:highlight (input.hidden-input)
     -0:44.1.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -0:31.4.0 gpp-compiler:compile (div.line.cursor-line)
```

### Non-Core Packages

```
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-python-run 0.9.7 
busy-signal 2.0.1 
gpp-compiler 3.0.7 
ide-c-cpp 0.1.0 
ide-java 0.9.1 
ide-python 1.9.7 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
```

**Comment by sirhikesalot** [comment]
Also getting this error on MacOS Monterey

**Comment by USS-SmauG** [comment]
The same here:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.0.1
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:135

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -2:04.3.0 application:reopen-project (div#add-projects-view.)
     -1:52.8.0 gpp-compiler:tree-compile (span.name.icon.cpp-icon.medium-blue)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
data-atom 0.29.1 
file-icons 2.1.47 
gpp-compiler 3.0.7 
minimap 4.40.0 
```

**Comment by macjaiswal100** [comment]
/* Calculate Ramesh's gross salary */
#include <stdio.h>
int main()
{
        float bp,da,hra,grpay ;
        printf("\nEnter Basic Salary of Ramesh:");
        scanf("%f",&bp);
        da = 0.4*bp;
        hra = 0.2*bp;
        grpay = bp+da+hra;
        printf("Basic Salary of Ramesh = %f\n",bp);
        printf("Dearness Allowance = %f\n",da);
        printf("House Rent Allowance = %f\n",hra);
        printf("Gross Pay of Ramesh is %fn",grpay);
        return 0;
}

**Comment by macjaiswal100** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Kali GNU/Linux
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7


### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:135

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -4:52.8.0 core:paste (div.highlights)
     -4:42.9.0 gpp-compiler:compile (div.highlights)
```

### Non-Core Packages

```
busy-signal 2.0.1 
gpp-compiler 3.0.7 
switch-header-source 0.34.5 
```

**Comment by mrityunjai01** [comment]
How to fix it?

**Comment by macjaiswal100** [comment]
TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at ChildProcess.<anonymous> (/home/kali/.atom/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)

**Comment by macjaiswal100** [comment]
TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at ChildProcess.<anonymous> (/home/kali/.atom/packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)

**Comment by xamer18** [comment]
Hi! I have the same error and I don't understand what I need to do. Can somebody help me please ? :/

**Comment by Alberto23450** [comment]
> The same here:
> 
> [Enter steps to reproduce:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.58.0 x64 **Electron**: 9.4.4 **OS**: macOS 12.0.1 **Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7
> 
> ### Stack Trace
> Uncaught TypeError: Callback must be a function. Received undefined
> 
> ```
> At fs.js:135
> 
> TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
>     at maybeCallback (fs.js:135:9)
>     at Object.writeFile (fs.js:1234:14)
>     at /packages/gpp-compiler/index.js:299:12)
>     at ChildProcess.emit (events.js:223:5)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Socket.<anonymous> (internal/child_process.js:430:11)
>     at Socket.emit (events.js:223:5)
>     at Pipe.<anonymous> (net.js:664:12)
> ```
> 
> ### Commands
> ```
>      -2:04.3.0 application:reopen-project (div#add-projects-view.)
>      -1:52.8.0 gpp-compiler:tree-compile (span.name.icon.cpp-icon.medium-blue)
> ```
> 
> ### Non-Core Packages
> ```
> atom-beautify 0.33.4 
> data-atom 0.29.1 
> file-icons 2.1.47 
> gpp-compiler 3.0.7 
> minimap 4.40.0 
> ```

can you explain step by step how I have to do in order to make the compiler work? what actions should i perform?

**Comment by Blixer4** [comment]
this problem still fundamentally remains is there any quit solution for this I have been searching on youtube but unfortunately I didn't found a solution for that particular problem any green flag ?
