### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by Dopeasent** [kriscross07/atom-gpp-compiler#400]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Linux Mint
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:135

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at /packages/gpp-compiler/index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
     -6:35 gpp-compiler:compile (div.highlights)
     -4:42 pane:split-up-and-copy-active-item (code.)
     -4:34.4.0 pane:close (div.item-views)
 13x -2:47.6.0 gpp-compiler:gdb (input.hidden-input)
     -0:11.4.0 intentions:highlight (input.hidden-input)
     -0:11.2.0 editor:toggle-line-comments (input.hidden-input)
     -0:09.6.0 intentions:highlight (input.hidden-input)
     -0:09.3.0 core:save (input.hidden-input)
     -0:07.7.0 gpp-compiler:gdb (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
color-picker 2.3.0 
emmet 2.4.3 
eslint 0.15.0 
file-icons 2.1.47 
ftp-remote-edit 0.18.2 
gpp-compiler 3.0.7 
highlight-selected 0.17.0 
Hydrogen 2.16.3 
ide-c-cpp 0.1.0 
ide-cpp 0.1.0 
intentions 2.1.1 
kite 0.206.0 
linter 3.4.0 
linter-gcc 0.9.0 
linter-pycodestyle 2.1.3 
linter-ui-default 3.4.1 
minimap 4.40.0 
minimap-highlight-selected 4.6.6 
php-twig 4.0.0 
pigments 0.40.6 
platformio-ide-terminal 2.10.1 
script 3.32.2 
switch-header-source 0.34.5 
```

**Comment by pranavpandey48** [comment]
How to solve this problem

**Comment by Kxyda** [comment]
How can i solve this problem :cc ?

**Comment by Blixer4** [comment]
How Can I solve this Problem ???????

**Comment by Harman-khurmi** [comment]
how to fix this one??

**Comment by 7bhainikhil** [comment]
**I am facing same issue please help me to solve this**  @Harman-khurmi  @Blixer4 @Kxyda

**Comment by pyrovibez** [comment]
How can I fix this problem?

**Comment by Pratik900** [comment]
How to solve this issue???

**Comment by Keymaker63** [comment]
Ok? So?
How do we solve this??

Atom is useless if the compiler doesn't work.
Why should I have 10 different programs for a few lines of codes?

**Comment by DariushMazlumi** [comment]
Hi everyone
I also faced the same error recently. but my previous experience with similar problem suggested me that maybe the path to my code contains less common characters or symbols.
![Screenshot 2022-03-02 190441](https://user-images.githubusercontent.com/30628454/156890522-59f3e9e8-6e84-4776-9b9b-d3d5492d0af6.png)
![Screenshot 2022-03-05 191434](https://user-images.githubusercontent.com/30628454/156890528-75756d89-887c-4830-a74a-d585c188a4b9.png)
notice the top left of provided screen shots, displaying the code's path. the first contains دسکتاپ (which means desktop in persian). the latter only contains ascii alphabet characters.  I'm not exactly aware what conditions in code's path make this problem, but I think changing your file's path so it contains english letters only, which perhaps yours isn't, worths giving a shot.
hope it helps somebody

**Comment by vydramain** [comment]
For me adding `-c -Wall -std=c++17` to "C++ Compiler Options" helps.

But I still can't start any file because my terminal says me: "There was an error creating the child process for this terminal. Failed to execute child process “/tmp/main”: Failed to execve: Permission denied"

**Comment by DariushMazlumi** [comment]
Hi everyone
as an alternative, you can use [this package](https://atom.io/packages/gcc-make-run). its working on my machine.
