### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by itzzexcel** [kriscross07/atom-gpp-compiler#409]
#### Stack Trace:

```
TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at ChildProcess.<anonymous> (C:\Users\anon\.atom\packages\gpp-compiler\index.js:299:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
Error at fs.js:135
fs.js : 1234 : 14
gpp-compiler\index.js:299:12
events.js:223:5
(internal/child_process.js:283:5

Steps to Reproduce:

- Debug a Simple C++ or C File

***Screenshot:***

![image](https://user-images.githubusercontent.com/98148217/167775407-97f09e9b-456e-4a09-868d-93d9504d25e5.png)

Additional Info:
OS: Windows 11 Home
Debugger / Compiler: GCC
Application: [Atom](https://atom.io/) by GitHub

**Comment by tushar4422** [comment]
You should have done any typing error in the program.

**Comment by itzzexcel** [comment]
Oh, I hadn't noticed, thanks for letting me know, I'll close the issue
