### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by haochengz** [kriscross07/atom-gpp-compiler#46]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package, v3.0.7
### Stack Trace

Uncaught TypeError: Bad argument

```
At internal/child_process.js:278

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:379:9)
    at compile (C:\Users\zhc\.atom\packages\gpp-compiler\index.js:274:31)
    at compileFile (C:\Users\zhc\.atom\packages\gpp-compiler\index.js:216:5)
    at atom-text-editor.subscriptions.add.atom.commands.add.gpp-compiler:compile (C:\Users\zhc\.atom\packages\gpp-compiler\index.js:23:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\zhc\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\zhc\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\zhc\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\zhc\AppData\Local\atom\app-1.10.2\resources\app.asar\src\atom-environment.js:1115:28)
    at EventEmitter.outerCallback (C:\Users\zhc\AppData\Local\atom\app-1.10.2\resources\app.asar\src\application-delegate.js:342:25)
    at emitThree (events.js:110:13)
    at EventEmitter.emit (events.js:188:7)
```
### Commands

```
  2x -1:46.5.0 gpp-compiler:compile (atom-text-editor.editor.is-focused)
     -1:12.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:11.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:11.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:10.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:10.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:10.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:09.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:08.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:02.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:56.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:52.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:47.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.1.0 gpp-compiler:compile (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "gpp-compiler": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.9.0 (active)
gpp-compiler, v3.0.7 (active)
language-cpp14, v0.6.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by asa1525** [comment]
same

**Comment by dmaisano** [comment]
Getting the same error.

Atom version: 1.10.2
gpp-compiler version: 3.0.7

**Comment by kant-shashi** [comment]
Getting same error on Mac.
Atom version: 1.10.2

**Comment by josephsieh** [comment]
Same error, 
Atom 1.11.1, Xcode 8.0
Mac OS 10.12

`[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package, v3.0.7

### Stack Trace

Uncaught TypeError: Bad argument

```
At internal/child_process.js:278

TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:379:9)
    at compile (/Users/xxxx/.atom/packages/gpp-compiler/index.js:274:31)
    at compileFile (/Users/xxxx/.atom/packages/gpp-compiler/index.js:216:5)
    at atom-text-editor.subscriptions.add.atom.commands.add.gpp-compiler:compile (/Users/xxxx/.atom/packages/gpp-compiler/index.js:23:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:33.3.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused)
     -0:00.0 gpp-compiler:compile (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-ctags",
      "minimap",
      "linter-cpplint",
      "linter-clang",
      "linter",
      "linter-chktex"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

``` coffee
# User
atom-ctags, v5.0.0 (inactive)
autocomplete-clang, v0.10.0 (active)
clang-format, v1.25.0 (active)
docblockr, v0.8.7 (active)
git-time-machine, v1.5.3 (inactive)
gpp-compiler, v3.0.7 (active)
language-cpp14, v0.6.2 (active)
linter, v1.11.18 (inactive)
linter-chktex, v1.3.0 (inactive)
linter-clang, v3.4.4 (inactive)
linter-cpplint, v1.0.1 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

`

**Comment by AslamGeek** [comment]
Hey guys,
I had the same issue.
However I solved it.
Just cut/paste all your downloaded packages from location to somewhere on your computer and then just install "gpp-compiler" & save your cpp code & hit F5 button. Boom!!! Output on cmd.
My packages were here "C:\Users\USER(dot)atom\packages\list of packages here".

Here USER is my pc name, in that dir you will find .atom dir, all packages were resided here.

Try this one guys, I hope this trick will also work for you :)

**Comment by artus9033** [comment]
shaikk123's workaround worked for me

**Comment by unsky** [comment]
这个问题我遇到了，而且解决了，卸载掉cpp14特性就行了，不支持。。language-cpp14,

**Comment by leo-mao** [comment]
Getting the same error on Manjaro

**Comment by unsky** [comment]
Hey,
 I had the same issue,
 but t I solved it.
The plug is not support cpp14. 
Because of the installing of language-cpp14, the plug will have this issue.
So...
uninstall cpp14..

**Comment by leo-mao** [comment]
@unsky 
有点没懂你的意思，卸载C++14？是卸载clang/GCC吗，还是滚回旧版本，你是在什么操作系统环境下？

**Comment by unsky** [comment]
@leo-mao 卸载language-cpp14这个插件

**Comment by preetidevi** [comment]
Please someone help me i am not able to handle this prob. Tried the above solution but it didn't worked.....

**Comment by fusion809** [comment]
I also get this error on Fedora 25 with Atom 1.12.7.

**Comment by li-bin-bin** [comment]
Had this error today after installing [language-cpp14](https://atom.io/packages/language-cpp14) package. So as @unsky said - just remove this package, restart Atom and it will be work fine. 

Debian 8
Atom 1.12.7

**Comment by dollylly** [comment]
the same. But i haven't install language-cpp14. So what should i do?_(:зゝ∠)__(:зゝ∠)_

**Comment by AlexKrueger** [comment]
This issue is still occurring! Any workarounds?

**Comment by DerekGary** [comment]
Try this if you haven't already (for Windows 10):
1.) Make sure you have downloaded the MinGW Installation Manager installed on your computer.
2.) Install mingw32-gcc-g++ from the basic setup. (This is the compiler you need)
3.) Search for 'View Advanced System Settings' and click on 'Environmental Variables' at the bottom of the Advanced System Settings menu.
4. Double click PATH, click the new button, and paste in "C:\MinGW\bin".
(This could be different depending on if you elected to install it to a different location.) 

This error is more than likely thrown because you have not added C:\MinGW\bin (or where ever you installed MinGW to) to your PATH. Atom is attempting to call g++ to compile your program, but your computer does not know where to search for the C++ compiler. 

Adding the MinGW bin directory to your PATH ensures that Atom can call upon it without knowing the exact location of the file on your system.

If this doesn't fix your issue, then you could possibly follow the other solutions above.

**Comment by DerekGary** [comment]
Try this if you haven't already (for Windows 10):
1.) Make sure you have the MinGW Installation Manager installed on your computer.
2.) Install mingw32-gcc-g++ from the basic setup. (This is the compiler you need to compile C++.)
3.) Search for 'View Advanced System Settings' on Windows and click on 'Environmental Variables...' at the bottom of the Advanced System Settings menu.
4. Double click PATH, click the new button, and paste in "C:\MinGW\bin".
(This could be different depending on if you elected to install it to a different location.)

This error is more than likely thrown because C:\MinGW\bin (or where ever you installed MinGW to) has not been added to your PATH. Atom is attempting to call g++ to compile your program, but your computer does not know where to search for the C++ compiler.

Adding the MinGW bin directory to your PATH ensures that Atom can call upon it without knowing the exact location of the file on your system.

If this doesn't fix your issue, then you could possibly follow the other solutions above.

**Comment by AlexKrueger** [comment]
I have MacOS, have to use Unix.

**Comment by DerekGary** [comment]
@AlexKrueger Have you tried to install Xcode to see if that fixes your problem? I believe the Xcode IDE for Mac also comes with a C++ compiler, and it would be one of the easiest ways to ensure that you have one installed. The gpp-compiler package for Atom should be able to utilize the compiler downloaded with Xcode to help compile your program.

If that doesn't work, then you could always use Xcode instead of Atom until you can find a fix.

**Comment by AlexKrueger** [comment]
Yea. I have Xcode downloaded. A friend told me to use Clion. I think I will be using that for now.

**Comment by SilentCC** [comment]
I have downloaded Xcode.And I use Atom open the file written by Xcode and complie it.It will show this error.And I save as .cpp type.Then It works.

**Comment by taylorcoderer** [comment]
@unsky 大神我没有装language-cpp14这个插件啊，又是什么原因。我是想编译python

**Comment by MushfiqaAyesha** [comment]
How I solved it:-
1. Change the file name from "hello" to "hello.cpp"
2. Change code language to c++

Note that I was writing a c++ program.  This error was because not adding the extension in name.
