### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by JTmuciru** [kriscross07/atom-gpp-compiler#77]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package 3.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'getGrammar' of undefined

```
At C:\Users\joaqu\.atom\packages\gpp-compiler\index.js:141

TypeError: Cannot read property 'getGrammar' of undefined
    at getFileType (/packages/gpp-compiler/index.js:141:28)
    at /packages/gpp-compiler/index.js:23:23)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -4:05.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:49.5.0 core:confirm (input.hidden-input)
     -1:52.1.0 gpp-compiler:compile (input.hidden-input)
  2x -1:27.9.0 core:confirm (input.hidden-input)
  8x -0:33.3.0 core:backspace (input.hidden-input)
     -0:30.5.0 core:confirm (input.hidden-input)
     -0:25.1.0 gpp-compiler:compile (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-clang 0.10.0 
color-picker 2.2.5 
file-icons 2.0.15 
gpp-compiler 3.0.7 
minimap 4.25.7 
```

**Comment by Quill-89** [comment]
I've had this problem continuously, it's like i can't install packages
