### ISSUE TITLE
Error on Mac. What to do?

### ISSUE THREAD

**Issue by green1139** [kriscross07/atom-gpp-compiler#8]
**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package, v2.0.0

### Stack Trace

Uncaught TypeError: Incorrect value of args option

```
At child_process.js:312

TypeError: Incorrect value of args option
    at normalizeSpawnArguments (child_process.js:312:11)
    at Object.exports.spawn (child_process.js:345:38)
    at ChildProcess.<anonymous> (/Users/Siddhant/.atom/packages/gpp-compiler/index.js:86:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -3:59 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-material-ui)
     -3:02.5.0 gpp-compiler:treeCompile (li.file.entry.list-item.status-modified.selected)
  7x -2:25.5.0 core:backspace (atom-text-editor#gpp-compiler.gppOptions.editor.mini.is-focused)
     -2:22.7.0 core:confirm (atom-text-editor#gpp-compiler.gppOptions.editor.mini.is-focused)
  5x -2:16.3.0 core:backspace (atom-text-editor#gpp-compiler.gppOptions.editor.mini.is-focused)
     -2:09.6.0 gpp-compiler:treeCompile (li.file.entry.list-item.status-modified.selected)
  2x -2:05.9.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -1:54.2.0 core:backspace (atom-text-editor#gpp-compiler.gppOptions.editor.mini.is-focused)
     -1:41.3.0 gpp-compiler:treeCompile (span.name.icon.icon-file-text)
     -1:34.9.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:29.5.0 core:select-all (atom-text-editor#gpp-compiler.fileExtension.editor.mini.is-focused)
     -1:29 core:backspace (atom-text-editor#gpp-compiler.fileExtension.editor.mini.is-focused)
     -1:28.3.0 core:confirm (atom-text-editor#gpp-compiler.fileExtension.editor.mini.is-focused)
     -1:24.6.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -1:17 tree-view:remove (span.name.icon.icon-file-text)
     -0:01.6.0 gpp-compiler:treeCompile (li.file.entry.list-item.status-modified.selected)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-oclitnt"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "gpp-compiler": {}
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.1
atom-webbrowser, v2.1.4
auto-indent, v0.5.0
autocomplete-clang, v0.8.9
browser-plus, v0.0.54
file-icons, v1.6.14
gpp-compiler, v2.0.0
linter, v1.11.3
linter-clang, v3.4.4
navigate, v0.1.13
pdf-view, v0.39.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by kriscross07** [comment]
Thanks you for submitting this issue because I don't have access to a mac to test the package on, but the new version I just released should fix this issue.
Tell me if it works.

**Comment by green1139** [comment]
Well, It is still giving me errors:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.4
**Thrown From**: [gpp-compiler](https://github.com/kriscross07/atom-gpp-compiler) package, v2.0.0


### Stack Trace

Uncaught TypeError: Incorrect value of args option

```
At child_process.js:312

TypeError: Incorrect value of args option
    at normalizeSpawnArguments (child_process.js:312:11)
    at Object.exports.spawn (child_process.js:345:38)
    at ChildProcess.<anonymous> (/Users/Siddhant/.atom/packages/gpp-compiler/index.js:86:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:59.8.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
     -0:55.9.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:32.7.0 gpp-compiler:treeCompile (span.name.icon.icon-file-text)
     -0:18.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-material-ui)
     -0:01.5.0 gpp-compiler:treeCompile (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-oclitnt"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "gpp-compiler": {}
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.1
atom-webbrowser, v2.1.4
auto-indent, v0.5.0
autocomplete-clang, v0.8.9
browser-plus, v0.0.54
file-icons, v1.6.14
gpp-compiler, v2.0.1
linter, v1.11.3
linter-clang, v3.4.4
navigate, v0.1.13
pdf-view, v0.39.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by green1139** [comment]
Thanks! It works!

**Comment by kriscross07** [comment]
Good, glad to help!
